package com.hongshen.sran_service.dao;

import com.alibaba.fastjson.JSONObject;
import com.hongshen.sran_service.entity.UnicomAlarmLte;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface UnicomAlarmLteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_alarm_lte
     *
     * @mbggenerated
     */
    int insert(UnicomAlarmLte record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_alarm_lte
     *
     * @mbggenerated
     */
    int insertSelective(UnicomAlarmLte record);

    List<UnicomAlarmLte> getAllAlarmLte();

    List<JSONObject> getGroupAlarmByGroupNameLte(@Param("groupName")String groupName);

    UnicomAlarmLte getNodeAlarmByNodeNameLte(@Param("nodeName")String nodeName);

    JSONObject getCellAlarmByCellNameLte(@Param("cellName")String cellName);
}