package com.hongshen.sran_service.dao;

import com.hongshen.sran_service.entity.UnicomCellLte;
import org.springframework.stereotype.Repository;

@Repository
public interface UnicomCellLteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_cell_lte
     *
     * @mbggenerated
     */
    int insert(UnicomCellLte record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_cell_lte
     *
     * @mbggenerated
     */
    int insertSelective(UnicomCellLte record);
}