package com.hongshen.sran_service.dao;

import com.alibaba.fastjson.JSONObject;
import com.hongshen.sran_service.entity.UnicomQuotaThresholdGroupLte;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface UnicomQuotaThresholdGroupLteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_threshold_group_lte
     *
     * @mbggenerated
     */
    int insert(UnicomQuotaThresholdGroupLte record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_threshold_group_lte
     *
     * @mbggenerated
     */
    int insertSelective(UnicomQuotaThresholdGroupLte record);

    List<JSONObject> getThresholdGroupList();

    Integer setGroup(JSONObject quotaThres);
}