package com.hongshen.sran_service.dao;

import com.hongshen.sran_service.entity.UnicomQuotaNodeWcdma;

public interface UnicomQuotaNodeWcdmaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_node_wcdma
     *
     * @mbggenerated
     */
    int insert(UnicomQuotaNodeWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_node_wcdma
     *
     * @mbggenerated
     */
    int insertSelective(UnicomQuotaNodeWcdma record);
}