package com.hongshen.sran_service.dao;

import com.hongshen.sran_service.entity.UnicomAlarmLte;

public interface UnicomAlarmLteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_alarm_lte
     *
     * @mbggenerated
     */
    int insert(UnicomAlarmLte record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_alarm_lte
     *
     * @mbggenerated
     */
    int insertSelective(UnicomAlarmLte record);
}