package com.hongshen.sran_service.dao;

import com.hongshen.sran_service.entity.UnicomQuotaCellWcdma;

public interface UnicomQuotaCellWcdmaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_cell_wcdma
     *
     * @mbggenerated
     */
    int insert(UnicomQuotaCellWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_cell_wcdma
     *
     * @mbggenerated
     */
    int insertSelective(UnicomQuotaCellWcdma record);
}