package com.hongshen.sran_service.dao;

import com.hongshen.sran_service.entity.UnicomQuotaHistoryNodeLte;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface UnicomQuotaHistoryNodeLteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_history_node_lte
     *
     * @mbggenerated
     */
    int insert(UnicomQuotaHistoryNodeLte record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_history_node_lte
     *
     * @mbggenerated
     */
    int insertSelective(UnicomQuotaHistoryNodeLte record);

    int getLevelByName(@Param("nodeName") String nodeName);
}