package com.hongshen.sran_service.dao;

import com.hongshen.sran_service.entity.UnicomQuotaCellTempWcdma;

public interface UnicomQuotaCellTempWcdmaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_cell_temp_wcdma
     *
     * @mbggenerated
     */
    int insert(UnicomQuotaCellTempWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_cell_temp_wcdma
     *
     * @mbggenerated
     */
    int insertSelective(UnicomQuotaCellTempWcdma record);
}