package com.hongshen.sran_service.dao;

import com.hongshen.sran_service.entity.UnicomUserAuthorityWcdma;

public interface UnicomUserAuthorityWcdmaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_user_authority_wcdma
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String loginName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_user_authority_wcdma
     *
     * @mbggenerated
     */
    int insert(UnicomUserAuthorityWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_user_authority_wcdma
     *
     * @mbggenerated
     */
    int insertSelective(UnicomUserAuthorityWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_user_authority_wcdma
     *
     * @mbggenerated
     */
    UnicomUserAuthorityWcdma selectByPrimaryKey(String loginName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_user_authority_wcdma
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UnicomUserAuthorityWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_user_authority_wcdma
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UnicomUserAuthorityWcdma record);
}