package com.hongshen.sran_service.dao;

import com.hongshen.sran_service.entity.UnicomQuotaThresholdCellWcdma;

public interface UnicomQuotaThresholdCellWcdmaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_threshold_cell_wcdma
     *
     * @mbggenerated
     */
    int insert(UnicomQuotaThresholdCellWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_threshold_cell_wcdma
     *
     * @mbggenerated
     */
    int insertSelective(UnicomQuotaThresholdCellWcdma record);
}