package com.hongshen.sran_service.dao;

import com.hongshen.sran_service.entity.UnicomAlarmTempLte;

public interface UnicomAlarmTempLteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_alarm_temp_lte
     *
     * @mbggenerated
     */
    int insert(UnicomAlarmTempLte record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_alarm_temp_lte
     *
     * @mbggenerated
     */
    int insertSelective(UnicomAlarmTempLte record);
}