package com.hongshen.sran_service.dao;

import com.hongshen.sran_service.entity.UnicomCounterLte;

public interface UnicomCounterLteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_counter_lte
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_counter_lte
     *
     * @mbggenerated
     */
    int insert(UnicomCounterLte record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_counter_lte
     *
     * @mbggenerated
     */
    int insertSelective(UnicomCounterLte record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_counter_lte
     *
     * @mbggenerated
     */
    UnicomCounterLte selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_counter_lte
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UnicomCounterLte record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_counter_lte
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UnicomCounterLte record);
}