package com.hongshen.sran_service.dao;

import com.hongshen.sran_service.entity.UnicomAlarmIndex;

public interface UnicomAlarmIndexMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_alarm_index
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String alarmNameId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_alarm_index
     *
     * @mbggenerated
     */
    int insert(UnicomAlarmIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_alarm_index
     *
     * @mbggenerated
     */
    int insertSelective(UnicomAlarmIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_alarm_index
     *
     * @mbggenerated
     */
    UnicomAlarmIndex selectByPrimaryKey(String alarmNameId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_alarm_index
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UnicomAlarmIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_alarm_index
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UnicomAlarmIndex record);
}