package com.hongshen.sran_service.dao;

import com.hongshen.sran_service.entity.UnicomAlarmLibraryWcdma;

public interface UnicomAlarmLibraryWcdmaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_alarm_library_wcdma
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String alarmName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_alarm_library_wcdma
     *
     * @mbggenerated
     */
    int insert(UnicomAlarmLibraryWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_alarm_library_wcdma
     *
     * @mbggenerated
     */
    int insertSelective(UnicomAlarmLibraryWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_alarm_library_wcdma
     *
     * @mbggenerated
     */
    UnicomAlarmLibraryWcdma selectByPrimaryKey(String alarmName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_alarm_library_wcdma
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UnicomAlarmLibraryWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_alarm_library_wcdma
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UnicomAlarmLibraryWcdma record);
}