package com.hongshen.sran_service.dao;

import com.hongshen.sran_service.entity.UnicomQuotaGroupTempLte;

public interface UnicomQuotaGroupTempLteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_group_temp_lte
     *
     * @mbggenerated
     */
    int insert(UnicomQuotaGroupTempLte record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_group_temp_lte
     *
     * @mbggenerated
     */
    int insertSelective(UnicomQuotaGroupTempLte record);
}