package com.hongshen.sran_service.dao;

import com.alibaba.fastjson.JSONObject;
import com.hongshen.sran_service.entity.UnicomAuthorityLte;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface UnicomAuthorityLteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_authority_lte
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String authorityName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_authority_lte
     *
     * @mbggenerated
     */
    int insert(UnicomAuthorityLte record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_authority_lte
     *
     * @mbggenerated
     */
    int insertSelective(UnicomAuthorityLte record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_authority_lte
     *
     * @mbggenerated
     */
    UnicomAuthorityLte selectByPrimaryKey(String authorityName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_authority_lte
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UnicomAuthorityLte record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_authority_lte
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UnicomAuthorityLte record);

    List<JSONObject> getAuthorityList();

    int updateAuthority(@Param("authorityName")String authorityName,@Param("param") JSONObject param);

    int addAuthority(@Param("param") JSONObject param);

    int deleteAuthority(@Param("authorityName")String authorityName);
}