package com.hongshen.sran_service.dao;

import com.hongshen.sran_service.entity.UnicomQuotaGroupTempWcdma;

public interface UnicomQuotaGroupTempWcdmaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_group_temp_wcdma
     *
     * @mbggenerated
     */
    int insert(UnicomQuotaGroupTempWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_group_temp_wcdma
     *
     * @mbggenerated
     */
    int insertSelective(UnicomQuotaGroupTempWcdma record);
}