package com.hongshen.sran_service.dao;

import com.hongshen.sran_service.entity.UnicomCounterWcdma;

public interface UnicomCounterWcdmaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_counter_wcdma
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_counter_wcdma
     *
     * @mbggenerated
     */
    int insert(UnicomCounterWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_counter_wcdma
     *
     * @mbggenerated
     */
    int insertSelective(UnicomCounterWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_counter_wcdma
     *
     * @mbggenerated
     */
    UnicomCounterWcdma selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_counter_wcdma
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UnicomCounterWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_counter_wcdma
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UnicomCounterWcdma record);
}