package com.hongshen.sran_service.dao;

import com.alibaba.fastjson.JSONObject;
import com.hongshen.sran_service.entity.UnicomQuotaHistoryGroupWcdma;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.Date;
import java.util.List;

@Repository
public interface UnicomQuotaHistoryGroupWcdmaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_history_group_wcdma
     *
     * @mbggenerated
     */
    int insert(UnicomQuotaHistoryGroupWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_history_group_wcdma
     *
     * @mbggenerated
     */
    int insertSelective(UnicomQuotaHistoryGroupWcdma record);

    Date getQuotaLastUpdateTime();

    JSONObject getQuota(@Param("groupName")String groupName,
                        @Param("time")String time);

    JSONObject getLevel(@Param("groupName") String groupName,
                        @Param("time")String time);

    List<JSONObject> getQuotas(@Param("start")Date start,
                               @Param("end")Date end,
                               @Param("condition")String condition);

    void addQuotaHistoryGroupList(@Param("cloumns")List<String> cloumns,
                                  @Param("valueList")List<String> valueList);

    List<JSONObject> getGroupTime();
}