package com.hongshen.sran_service.dao;

import com.hongshen.sran_service.entity.UnicomCacheLte;

public interface UnicomCacheLteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_cache_lte
     *
     * @mbggenerated
     */
    int insert(UnicomCacheLte record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_cache_lte
     *
     * @mbggenerated
     */
    int insertSelective(UnicomCacheLte record);
}