package com.hongshen.sran_service.dao;

import com.hongshen.sran_service.entity.UnicomCounterHistoryLte;

public interface UnicomCounterHistoryLteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_counter_history_lte
     *
     * @mbggenerated
     */
    int insert(UnicomCounterHistoryLte record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_counter_history_lte
     *
     * @mbggenerated
     */
    int insertSelective(UnicomCounterHistoryLte record);
}