package com.hongshen.sran_service.dao;

import com.hongshen.sran_service.entity.UnicomQuotaNodeLte;

public interface UnicomQuotaNodeLteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_node_lte
     *
     * @mbggenerated
     */
    int insert(UnicomQuotaNodeLte record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_node_lte
     *
     * @mbggenerated
     */
    int insertSelective(UnicomQuotaNodeLte record);
}