package com.hongshen.sran_service.dao;

import com.hongshen.sran_service.entity.UnicomCounterWcdma;
import org.springframework.stereotype.Repository;

import java.util.Map;
@Repository
public interface UnicomCounterWcdmaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_counter_wcdma
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_counter_wcdma
     *
     * @mbggenerated
     */
    int insert(UnicomCounterWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_counter_wcdma
     *
     * @mbggenerated
     */
    int insertSelective(UnicomCounterWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_counter_wcdma
     *
     * @mbggenerated
     */
    UnicomCounterWcdma selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_counter_wcdma
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UnicomCounterWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_counter_wcdma
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UnicomCounterWcdma record);

    Map<String,Object> getCounterMap();

    Map<String,Object> resetCounterMap();

    Map<String,Object> getQuotaMap();

    Map<String,Object> restQuotaMap();

    Map<String,Object> getGroupThresholdMap();

    Map<String,Object> restGroupThresholdMap();
}