package com.hongshen.sran_service.dao;

import com.hongshen.sran_service.entity.UnicomAuthorityLte;
import org.springframework.stereotype.Repository;

import java.util.Map;
@Repository
public interface UnicomAuthorityLteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_authority_lte
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String authorityName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_authority_lte
     *
     * @mbggenerated
     */
    int insert(UnicomAuthorityLte record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_authority_lte
     *
     * @mbggenerated
     */
    int insertSelective(UnicomAuthorityLte record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_authority_lte
     *
     * @mbggenerated
     */
    UnicomAuthorityLte selectByPrimaryKey(String authorityName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_authority_lte
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UnicomAuthorityLte record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_authority_lte
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UnicomAuthorityLte record);


    Map<String,Object> getUserAuthorty(String name);
}