package com.hongshen.sran_service.dao;

import com.hongshen.sran_service.entity.UnicomProtectLte;

public interface UnicomProtectLteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_protect_lte
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String nodeName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_protect_lte
     *
     * @mbggenerated
     */
    int insert(UnicomProtectLte record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_protect_lte
     *
     * @mbggenerated
     */
    int insertSelective(UnicomProtectLte record);
}