package com.hongshen.sran_service.dao;

import com.hongshen.sran_service.entity.UnicomAlarmWcdma;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface UnicomAlarmWcdmaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_alarm_wcdma
     *
     * @mbggenerated
     */
    int insert(UnicomAlarmWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_alarm_wcdma
     *
     * @mbggenerated
     */
    int insertSelective(UnicomAlarmWcdma record);

    List<UnicomAlarmWcdma> getAllAlarmWcdma();
}