package com.hongshen.sran_service.dao;

import com.alibaba.fastjson.JSONObject;
import com.hongshen.sran_service.entity.UnicomGroupTaskWcdma;
import org.springframework.stereotype.Repository;

@Repository
public interface UnicomGroupTaskWcdmaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_group_task_wcdma
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String taskName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_group_task_wcdma
     *
     * @mbggenerated
     */
    int insert(UnicomGroupTaskWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_group_task_wcdma
     *
     * @mbggenerated
     */
    int insertSelective(UnicomGroupTaskWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_group_task_wcdma
     *
     * @mbggenerated
     */
    UnicomGroupTaskWcdma selectByPrimaryKey(String taskName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_group_task_wcdma
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UnicomGroupTaskWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_group_task_wcdma
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UnicomGroupTaskWcdma record);

    JSONObject getTaskInfo(String loginName);
}