package com.hongshen.sran_service.dao;

import com.hongshen.sran_service.entity.UnicomCommandWcdma;

public interface UnicomCommandWcdmaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_command_wcdma
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_command_wcdma
     *
     * @mbggenerated
     */
    int insert(UnicomCommandWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_command_wcdma
     *
     * @mbggenerated
     */
    int insertSelective(UnicomCommandWcdma record);
}