package com.hongshen.sran_service.dao;

import com.hongshen.sran_service.entity.UnicomProtectWcdma;
import org.springframework.stereotype.Repository;

import java.util.Map;

@Repository
public interface UnicomProtectWcdmaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_protect_wcdma
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String nodeName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_protect_wcdma
     *
     * @mbggenerated
     */
    int insert(UnicomProtectWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_protect_wcdma
     *
     * @mbggenerated
     */
    int insertSelective(UnicomProtectWcdma record);

    Map<String,Object> getProtect();
}