package com.hongshen.sran_service.dao;

import com.hongshen.sran_service.entity.UnicomTaskWcdma;
import com.hongshen.sran_service.entity.UnicomTaskWcdmaWithBLOBs;

public interface UnicomTaskWcdmaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_task_wcdma
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_task_wcdma
     *
     * @mbggenerated
     */
    int insert(UnicomTaskWcdmaWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_task_wcdma
     *
     * @mbggenerated
     */
    int insertSelective(UnicomTaskWcdmaWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_task_wcdma
     *
     * @mbggenerated
     */
    UnicomTaskWcdmaWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_task_wcdma
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UnicomTaskWcdmaWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_task_wcdma
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(UnicomTaskWcdmaWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_task_wcdma
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UnicomTaskWcdma record);
}