package com.hongshen.sran_service.dao;

import com.hongshen.sran_service.entity.UnicomQuotaCellLte;

public interface UnicomQuotaCellLteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_cell_lte
     *
     * @mbggenerated
     */
    int insert(UnicomQuotaCellLte record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_cell_lte
     *
     * @mbggenerated
     */
    int insertSelective(UnicomQuotaCellLte record);
}