package com.hongshen.sran_service.dao;

import com.alibaba.fastjson.JSONObject;
import com.hongshen.sran_service.entity.UnicomCellWcdma;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface UnicomCellWcdmaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_cell_wcdma
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String cellName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_cell_wcdma
     *
     * @mbggenerated
     */
    int insert(UnicomCellWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_cell_wcdma
     *
     * @mbggenerated
     */
    int insertSelective(UnicomCellWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_cell_wcdma
     *
     * @mbggenerated
     */
    UnicomCellWcdma selectByPrimaryKey(String cellName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_cell_wcdma
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UnicomCellWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_cell_wcdma
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(UnicomCellWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_cell_wcdma
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UnicomCellWcdma record);

    JSONObject getCellInfo(@Param("cellName") String cellName);

    List<JSONObject> getCellListByNode(@Param("nodeName")String nodeName);

    List<String> getCellNameListByNode(@Param("nodeName")String nodeName);

    List<String> getCellNameList();

    List<JSONObject> getCellInfoList();

    List<String> getCellNameListByNodeNameList(@Param("nodeNameList")List<String> nodeNameList);
}