package com.hongshen.sran_service.dao;

import com.hongshen.sran_service.entity.UnicomQuotaCellTempLte;

public interface UnicomQuotaCellTempLteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_cell_temp_lte
     *
     * @mbggenerated
     */
    int insert(UnicomQuotaCellTempLte record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_cell_temp_lte
     *
     * @mbggenerated
     */
    int insertSelective(UnicomQuotaCellTempLte record);
}