package com.hongshen.sran_service.dao;

import com.alibaba.fastjson.JSONObject;
import com.hongshen.sran_service.entity.UnicomQuotaThresholdNodeLte;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface UnicomQuotaThresholdNodeLteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_threshold_node_lte
     *
     * @mbggenerated
     */
    int insert(UnicomQuotaThresholdNodeLte record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_threshold_node_lte
     *
     * @mbggenerated
     */
    int insertSelective(UnicomQuotaThresholdNodeLte record);

    List<JSONObject> getThresholdList();

    Integer setThreshold(JSONObject params);
}