package com.hongshen.sran_service.dao;

import com.alibaba.fastjson.JSONObject;
import com.hongshen.sran_service.entity.UnicomGroupInfoIndexWcdma;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface UnicomGroupInfoIndexWcdmaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_group_info_index_wcdma
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_group_info_index_wcdma
     *
     * @mbggenerated
     */
    int insert(UnicomGroupInfoIndexWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_group_info_index_wcdma
     *
     * @mbggenerated
     */
    int insertSelective(UnicomGroupInfoIndexWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_group_info_index_wcdma
     *
     * @mbggenerated
     */
    UnicomGroupInfoIndexWcdma selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_group_info_index_wcdma
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UnicomGroupInfoIndexWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_group_info_index_wcdma
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UnicomGroupInfoIndexWcdma record);

    List<JSONObject> getInfoIndexList();
}