package com.hongshen.sran_service.dao;

import com.hongshen.sran_service.entity.UnicomCacheWcdma;

public interface UnicomCacheWcdmaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_cache_wcdma
     *
     * @mbggenerated
     */
    int insert(UnicomCacheWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_cache_wcdma
     *
     * @mbggenerated
     */
    int insertSelective(UnicomCacheWcdma record);
}