package com.hongshen.sran_service.dao;

import com.hongshen.sran_service.entity.UnicomQuotaHistoryGroupLte;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.Map;

@Repository
public interface UnicomQuotaHistoryGroupLteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_history_group_lte
     *
     * @mbggenerated
     */
    int insert(UnicomQuotaHistoryGroupLte record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_history_group_lte
     *
     * @mbggenerated
     */
    int insertSelective(UnicomQuotaHistoryGroupLte record);

    UnicomQuotaHistoryGroupLte getQuotaHistoryGroupLte(@Param("groupName")String groupName);

    Map<String,Object> getQuotaInfo();
}