package com.hongshen.sran_service.dao;

import com.alibaba.fastjson.JSONObject;
import com.hongshen.sran_service.entity.UnicomNodeLte;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import java.util.List;


@Repository
public interface UnicomNodeLteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_node_lte
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String nodeName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_node_lte
     *
     * @mbggenerated
     */
    int insert(UnicomNodeLte record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_node_lte
     *
     * @mbggenerated
     */
    int insertSelective(UnicomNodeLte record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_node_lte
     *
     * @mbggenerated
     */
    UnicomNodeLte selectByPrimaryKey(String nodeName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_node_lte
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UnicomNodeLte record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_node_lte
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UnicomNodeLte record);

    List<JSONObject> getNodeListByGroup(@Param("groupName") String groupName);

    List<JSONObject> getNodeLocationsByGroup(@Param("groupName") String groupName);
    
    List<String> getNodeNameListByGroup(@Param("groupName")String groupName);

    JSONObject getNodeLocation(@Param("nodeName")String nodeName);

    List<JSONObject> getNodeInfoList();

    List<String> getNodeNameList();

    List<JSONObject> getGroupList();

    //List<JSONObject> getGroupInfoList(); // 4g no group info

    List<String> getGroupNameList();

    JSONObject getNodeInfo(@Param("nodeName") String nodeName);

    List<JSONObject> getNodes(@Param("tableName") String tableName,@Param("name")String name);

}