package com.hongshen.sran_service.dao;

import com.hongshen.sran_service.entity.UnicomQuotaHistoryNodeWcdma;

public interface UnicomQuotaHistoryNodeWcdmaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_history_node_wcdma
     *
     * @mbggenerated
     */
    int insert(UnicomQuotaHistoryNodeWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_history_node_wcdma
     *
     * @mbggenerated
     */
    int insertSelective(UnicomQuotaHistoryNodeWcdma record);
}