package com.hongshen.sran_service.dao;

import com.alibaba.fastjson.JSONObject;
import com.hongshen.sran_service.entity.UnicomQuotaHistoryGroupWcdma;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface UnicomQuotaHistoryGroupWcdmaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_history_group_wcdma
     *
     * @mbggenerated
     */
    int insert(UnicomQuotaHistoryGroupWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_history_group_wcdma
     *
     * @mbggenerated
     */
    int insertSelective(UnicomQuotaHistoryGroupWcdma record);

    JSONObject getQuotaByName(@Param("groupName")String groupName);

    int getLevelByName(@Param("groupName") String groupName);
}