package com.hongshen.sran_service.dao;

import com.alibaba.fastjson.JSONObject;
import com.hongshen.sran_service.entity.UnicomRoomWcdma;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface UnicomRoomWcdmaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_room_wcdma
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String room);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_room_wcdma
     *
     * @mbggenerated
     */
    int insert(UnicomRoomWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_room_wcdma
     *
     * @mbggenerated
     */
    int insertSelective(UnicomRoomWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_room_wcdma
     *
     * @mbggenerated
     */
    UnicomRoomWcdma selectByPrimaryKey(String room);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_room_wcdma
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UnicomRoomWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_room_wcdma
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UnicomRoomWcdma record);

    List<JSONObject> getRoomLocationList();
}