package com.hongshen.sran_service.dao;

import com.hongshen.sran_service.entity.UnicomQuotaHistoryCellWcdma;

public interface UnicomQuotaHistoryCellWcdmaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_history_cell_wcdma
     *
     * @mbggenerated
     */
    int insert(UnicomQuotaHistoryCellWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_history_cell_wcdma
     *
     * @mbggenerated
     */
    int insertSelective(UnicomQuotaHistoryCellWcdma record);
}