package com.hongshen.sran_service.dao;

import com.hongshen.sran_service.entity.UnicomAlarmLibraryLte;

public interface UnicomAlarmLibraryLteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_alarm_library_lte
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String alarmName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_alarm_library_lte
     *
     * @mbggenerated
     */
    int insert(UnicomAlarmLibraryLte record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_alarm_library_lte
     *
     * @mbggenerated
     */
    int insertSelective(UnicomAlarmLibraryLte record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_alarm_library_lte
     *
     * @mbggenerated
     */
    UnicomAlarmLibraryLte selectByPrimaryKey(String alarmName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_alarm_library_lte
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UnicomAlarmLibraryLte record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_alarm_library_lte
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UnicomAlarmLibraryLte record);
}