package com.hongshen.sran_service.dao;

import com.hongshen.sran_service.entity.UnicomAlarmLibrary;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.Map;
@Repository
public interface UnicomAlarmLibraryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_alarm_library
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String alarmNameId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_alarm_library
     *
     * @mbggenerated
     */
    int insert(UnicomAlarmLibrary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_alarm_library
     *
     * @mbggenerated
     */
    int insertSelective(UnicomAlarmLibrary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_alarm_library
     *
     * @mbggenerated
     */
    UnicomAlarmLibrary selectByPrimaryKey(String alarmNameId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_alarm_library
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UnicomAlarmLibrary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_alarm_library
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UnicomAlarmLibrary record);

    Map<String,Object> getAlarmLibrary();

    Map<String,Object> getSpecifiedLibrary(String alarmNameId);


    void updateSpecifiedLibrary(@Param("alarmNameId") String alarmNameId,@Param("name") String name);
}