package com.hongshen.sran_service.dao;

import com.hongshen.sran_service.entity.UnicomQuotaThresholdCellLte;

public interface UnicomQuotaThresholdCellLteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_threshold_cell_lte
     *
     * @mbggenerated
     */
    int insert(UnicomQuotaThresholdCellLte record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_threshold_cell_lte
     *
     * @mbggenerated
     */
    int insertSelective(UnicomQuotaThresholdCellLte record);
}