package com.hongshen.sran_service.dao;

import com.alibaba.fastjson.JSONObject;
import com.hongshen.sran_service.entity.UnicomQuotaThresholdCellLte;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface UnicomQuotaThresholdCellLteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_threshold_cell_lte
     *
     * @mbggenerated
     */
    int insert(UnicomQuotaThresholdCellLte record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_threshold_cell_lte
     *
     * @mbggenerated
     */
    int insertSelective(UnicomQuotaThresholdCellLte record);

    List<JSONObject> getThresholdCellList();
}