package com.hongshen.sran_service.dao;

import com.hongshen.sran_service.entity.UnicomFormulaLte;
import org.springframework.stereotype.Repository;

@Repository
public interface UnicomFormulaLteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_formula_lte
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_formula_lte
     *
     * @mbggenerated
     */
    int insert(UnicomFormulaLte record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_formula_lte
     *
     * @mbggenerated
     */
    int insertSelective(UnicomFormulaLte record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_formula_lte
     *
     * @mbggenerated
     */
    UnicomFormulaLte selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_formula_lte
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UnicomFormulaLte record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_formula_lte
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UnicomFormulaLte record);
}