package com.hongshen.sran_service.dao;

import com.hongshen.sran_service.entity.UnicomNodeWcdma;

public interface UnicomNodeWcdmaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_node_wcdma
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String nodeName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_node_wcdma
     *
     * @mbggenerated
     */
    int insert(UnicomNodeWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_node_wcdma
     *
     * @mbggenerated
     */
    int insertSelective(UnicomNodeWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_node_wcdma
     *
     * @mbggenerated
     */
    UnicomNodeWcdma selectByPrimaryKey(String nodeName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_node_wcdma
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UnicomNodeWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_node_wcdma
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UnicomNodeWcdma record);
}