package com.hongshen.sran_service.dao;

import com.alibaba.fastjson.JSONObject;
import com.hongshen.sran_service.entity.UnicomNodeLte;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UnicomNodeLteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_node_lte
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String nodeName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_node_lte
     *
     * @mbggenerated
     */
    int insert(UnicomNodeLte record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_node_lte
     *
     * @mbggenerated
     */
    int insertSelective(UnicomNodeLte record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_node_lte
     *
     * @mbggenerated
     */
    UnicomNodeLte selectByPrimaryKey(String nodeName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_node_lte
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UnicomNodeLte record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_node_lte
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UnicomNodeLte record);

    List<JSONObject> getSpecifiedNodeList(@Param("groupName") String groupName, @Param("nodeName") String nodeName);
}