package com.hongshen.sran_service.dao;

import com.alibaba.fastjson.JSONObject;
import com.hongshen.sran_service.entity.UnicomCellWcdma;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface UnicomCellWcdmaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_cell_wcdma
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String cellName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_cell_wcdma
     *
     * @mbggenerated
     */
    int insert(UnicomCellWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_cell_wcdma
     *
     * @mbggenerated
     */
    int insertSelective(UnicomCellWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_cell_wcdma
     *
     * @mbggenerated
     */
    UnicomCellWcdma selectByPrimaryKey(String cellName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_cell_wcdma
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UnicomCellWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_cell_wcdma
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(UnicomCellWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_cell_wcdma
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UnicomCellWcdma record);

    List<JSONObject> getSpecifiedCellList(@Param("cellName") String cellName);


    List<JSONObject> getCellList(@Param("nodeName")String nodeName);

}