package com.hongshen.sran_service.dao;

import com.hongshen.sran_service.entity.UnicomQuotaGroupLte;

public interface UnicomQuotaGroupLteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_group_lte
     *
     * @mbggenerated
     */
    int insert(UnicomQuotaGroupLte record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_group_lte
     *
     * @mbggenerated
     */
    int insertSelective(UnicomQuotaGroupLte record);
}