package com.hongshen.sran_service.dao;

import com.alibaba.fastjson.JSONObject;
import com.hongshen.sran_service.entity.UnicomAlarmIndex;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface UnicomAlarmIndexMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_alarm_index
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String alarmNameId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_alarm_index
     *
     * @mbggenerated
     */
    int insert(UnicomAlarmIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_alarm_index
     *
     * @mbggenerated
     */
    int insertSelective(UnicomAlarmIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_alarm_index
     *
     * @mbggenerated
     */
    UnicomAlarmIndex selectByPrimaryKey(String alarmNameId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_alarm_index
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UnicomAlarmIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_alarm_index
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UnicomAlarmIndex record);

    int addAlarmIndex(@Param("param")JSONObject param);

    List<JSONObject> getAlarmByName(String alarmNameId, String alarmName);
}