package com.hongshen.sran_service.dao;

import com.alibaba.fastjson.JSONObject;
import com.hongshen.sran_service.entity.UnicomQuotaThresholdGroupWcdma;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface UnicomQuotaThresholdGroupWcdmaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_threshold_group_wcdma
     *
     * @mbggenerated
     */
    int insert(UnicomQuotaThresholdGroupWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_threshold_group_wcdma
     *
     * @mbggenerated
     */
    int insertSelective(UnicomQuotaThresholdGroupWcdma record);

    List<JSONObject> getThresholdGroupList();
}