package com.hongshen.sran_service.dao;

import com.hongshen.sran_service.entity.UnicomCellWcdma;

public interface UnicomCellWcdmaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_cell_wcdma
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String cellName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_cell_wcdma
     *
     * @mbggenerated
     */
    int insert(UnicomCellWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_cell_wcdma
     *
     * @mbggenerated
     */
    int insertSelective(UnicomCellWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_cell_wcdma
     *
     * @mbggenerated
     */
    UnicomCellWcdma selectByPrimaryKey(String cellName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_cell_wcdma
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UnicomCellWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_cell_wcdma
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(UnicomCellWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_cell_wcdma
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UnicomCellWcdma record);
}