package com.hongshen.sran_service.dao;

import com.hongshen.sran_service.entity.UnicomQuotaHistoryNodeLte;

public interface UnicomQuotaHistoryNodeLteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_history_node_lte
     *
     * @mbggenerated
     */
    int insert(UnicomQuotaHistoryNodeLte record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_history_node_lte
     *
     * @mbggenerated
     */
    int insertSelective(UnicomQuotaHistoryNodeLte record);
}