package com.hongshen.sran_service.dao;

import com.hongshen.sran_service.entity.UnicomQuotaNodeTempLte;

public interface UnicomQuotaNodeTempLteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_node_temp_lte
     *
     * @mbggenerated
     */
    int insert(UnicomQuotaNodeTempLte record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_node_temp_lte
     *
     * @mbggenerated
     */
    int insertSelective(UnicomQuotaNodeTempLte record);
}