package com.hongshen.sran_service.dao;

import com.hongshen.sran_service.entity.UnicomQuotaGroupWcdma;

public interface UnicomQuotaGroupWcdmaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_group_wcdma
     *
     * @mbggenerated
     */
    int insert(UnicomQuotaGroupWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_group_wcdma
     *
     * @mbggenerated
     */
    int insertSelective(UnicomQuotaGroupWcdma record);
}