package com.hongshen.sran_service.dao;

import com.alibaba.fastjson.JSONObject;
import com.hongshen.sran_service.entity.UnicomQuotaHistoryCellLte;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface UnicomQuotaHistoryCellLteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_history_cell_lte
     *
     * @mbggenerated
     */
    int insert(UnicomQuotaHistoryCellLte record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_history_cell_lte
     *
     * @mbggenerated
     */
    int insertSelective(UnicomQuotaHistoryCellLte record);

    JSONObject getQuotaByName(@Param("cellName")String cellName);

    int getLevelByName(@Param("cellName") String cellName);

    JSONObject getCellLevel(@Param("cellName")String cellName);
}