package com.hongshen.sran_service.dao;

import com.hongshen.sran_service.entity.UnicomCounterHistoryWcdma;

public interface UnicomCounterHistoryWcdmaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_counter_history_wcdma
     *
     * @mbggenerated
     */
    int insert(UnicomCounterHistoryWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_counter_history_wcdma
     *
     * @mbggenerated
     */
    int insertSelective(UnicomCounterHistoryWcdma record);
}