package com.hongshen.sran_service.dao;

import com.alibaba.fastjson.JSONObject;
import com.hongshen.sran_service.entity.UnicomQuotaHistoryNodeWcdma;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface UnicomQuotaHistoryNodeWcdmaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_history_node_wcdma
     *
     * @mbggenerated
     */
    int insert(UnicomQuotaHistoryNodeWcdma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unicom_quota_history_node_wcdma
     *
     * @mbggenerated
     */
    int insertSelective(UnicomQuotaHistoryNodeWcdma record);

    JSONObject getQuotaByName(@Param("nodeName")String nodeName);

    int getLevelByName(@Param("nodeName") String nodeName);
}