package com.hongshen.sran_service.dao;

import com.alibaba.fastjson.JSONArray;
import com.alibaba.fastjson.JSONObject;
import com.hongshen.sran_service.entity.User;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String loginName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    User selectByPrimaryKey(String loginName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(User record);

    List<JSONObject> getUserList();

    int updateUser(@Param("param") JSONObject param,@Param("userName") String userName);

//    int updateWcdmaAuth(@Param("roleList")List<JSONObject> roleList,@Param("loginName") String loginName);
//
//    int updateLteAuth(@Param("roleList")List<JSONObject> roleList,@Param("loginName") String loginName);

    int delteWcdmaAuth(@Param("loginName")String loginName);

    int delteLteAuth(@Param("loginName")String loginName);

    int addWcdmaAuth(@Param("roleList")List<String> roleList, @Param("loginName") String loginName);

    int addLteAuth(@Param("roleList")List<String> roleList, @Param("loginName") String loginName);

    int addUser(@Param("param") JSONObject param);

    List<JSONObject> getUserlistInfo(@Param("loginName")String loginName);

    List<JSONObject> getUserRolelistInfo(@Param("loginName")String loginName);

    int addUserRoleInfo(@Param("param")JSONObject param);

    int deleteUser(@Param("loginName") String loginName);

    int deleteUserRole(@Param("loginName")String loginName);
}