package com.hongshen.sran_service.entity;

import java.io.Serializable;

public class UnicomFormulaLte implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_formula_lte.quota_name
     *
     * @mbggenerated
     */
    private String quotaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_formula_lte.expression
     *
     * @mbggenerated
     */
    private String expression;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_formula_lte.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_formula_lte.status
     *
     * @mbggenerated
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_formula_lte.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_formula_lte.unit
     *
     * @mbggenerated
     */
    private Integer unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_formula_lte.hasTop10
     *
     * @mbggenerated
     */
    private Boolean hastop10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table unicom_formula_lte
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_formula_lte.quota_name
     *
     * @return the value of unicom_formula_lte.quota_name
     *
     * @mbggenerated
     */
    public String getQuotaName() {
        return quotaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_formula_lte.quota_name
     *
     * @param quotaName the value for unicom_formula_lte.quota_name
     *
     * @mbggenerated
     */
    public void setQuotaName(String quotaName) {
        this.quotaName = quotaName == null ? null : quotaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_formula_lte.expression
     *
     * @return the value of unicom_formula_lte.expression
     *
     * @mbggenerated
     */
    public String getExpression() {
        return expression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_formula_lte.expression
     *
     * @param expression the value for unicom_formula_lte.expression
     *
     * @mbggenerated
     */
    public void setExpression(String expression) {
        this.expression = expression == null ? null : expression.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_formula_lte.remark
     *
     * @return the value of unicom_formula_lte.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_formula_lte.remark
     *
     * @param remark the value for unicom_formula_lte.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_formula_lte.status
     *
     * @return the value of unicom_formula_lte.status
     *
     * @mbggenerated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_formula_lte.status
     *
     * @param status the value for unicom_formula_lte.status
     *
     * @mbggenerated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_formula_lte.type
     *
     * @return the value of unicom_formula_lte.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_formula_lte.type
     *
     * @param type the value for unicom_formula_lte.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_formula_lte.unit
     *
     * @return the value of unicom_formula_lte.unit
     *
     * @mbggenerated
     */
    public Integer getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_formula_lte.unit
     *
     * @param unit the value for unicom_formula_lte.unit
     *
     * @mbggenerated
     */
    public void setUnit(Integer unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_formula_lte.hasTop10
     *
     * @return the value of unicom_formula_lte.hasTop10
     *
     * @mbggenerated
     */
    public Boolean getHastop10() {
        return hastop10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_formula_lte.hasTop10
     *
     * @param hastop10 the value for unicom_formula_lte.hasTop10
     *
     * @mbggenerated
     */
    public void setHastop10(Boolean hastop10) {
        this.hastop10 = hastop10;
    }
}