package com.hongshen.sran_service.entity;

import java.io.Serializable;
import java.util.Date;

public class UnicomQuotaHistoryCellLte implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_quota_history_cell_lte.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_quota_history_cell_lte.time
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_quota_history_cell_lte.level
     *
     * @mbggenerated
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_quota_history_cell_lte.formula1
     *
     * @mbggenerated
     */
    private String formula1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_quota_history_cell_lte.formula2
     *
     * @mbggenerated
     */
    private String formula2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_quota_history_cell_lte.formula3
     *
     * @mbggenerated
     */
    private String formula3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_quota_history_cell_lte.formula4
     *
     * @mbggenerated
     */
    private String formula4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_quota_history_cell_lte.formula5
     *
     * @mbggenerated
     */
    private String formula5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_quota_history_cell_lte.formula6
     *
     * @mbggenerated
     */
    private String formula6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_quota_history_cell_lte.formula7
     *
     * @mbggenerated
     */
    private String formula7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_quota_history_cell_lte.formula8
     *
     * @mbggenerated
     */
    private String formula8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_quota_history_cell_lte.formula9
     *
     * @mbggenerated
     */
    private String formula9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_quota_history_cell_lte.formula10
     *
     * @mbggenerated
     */
    private String formula10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_quota_history_cell_lte.formula11
     *
     * @mbggenerated
     */
    private String formula11;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_quota_history_cell_lte.formula12
     *
     * @mbggenerated
     */
    private String formula12;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_quota_history_cell_lte.formula13
     *
     * @mbggenerated
     */
    private String formula13;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_quota_history_cell_lte.formula14
     *
     * @mbggenerated
     */
    private String formula14;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_quota_history_cell_lte.formula15
     *
     * @mbggenerated
     */
    private String formula15;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_quota_history_cell_lte.formula16
     *
     * @mbggenerated
     */
    private String formula16;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_quota_history_cell_lte.formula17
     *
     * @mbggenerated
     */
    private String formula17;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_quota_history_cell_lte.formula18
     *
     * @mbggenerated
     */
    private String formula18;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_quota_history_cell_lte.formula19
     *
     * @mbggenerated
     */
    private String formula19;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_quota_history_cell_lte.formula20
     *
     * @mbggenerated
     */
    private String formula20;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_quota_history_cell_lte.formula21
     *
     * @mbggenerated
     */
    private String formula21;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_quota_history_cell_lte.formula22
     *
     * @mbggenerated
     */
    private String formula22;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_quota_history_cell_lte.formula23
     *
     * @mbggenerated
     */
    private String formula23;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_quota_history_cell_lte.formula24
     *
     * @mbggenerated
     */
    private String formula24;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_quota_history_cell_lte.formula25
     *
     * @mbggenerated
     */
    private String formula25;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table unicom_quota_history_cell_lte
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_quota_history_cell_lte.name
     *
     * @return the value of unicom_quota_history_cell_lte.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_quota_history_cell_lte.name
     *
     * @param name the value for unicom_quota_history_cell_lte.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_quota_history_cell_lte.time
     *
     * @return the value of unicom_quota_history_cell_lte.time
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_quota_history_cell_lte.time
     *
     * @param time the value for unicom_quota_history_cell_lte.time
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_quota_history_cell_lte.level
     *
     * @return the value of unicom_quota_history_cell_lte.level
     *
     * @mbggenerated
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_quota_history_cell_lte.level
     *
     * @param level the value for unicom_quota_history_cell_lte.level
     *
     * @mbggenerated
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_quota_history_cell_lte.formula1
     *
     * @return the value of unicom_quota_history_cell_lte.formula1
     *
     * @mbggenerated
     */
    public String getFormula1() {
        return formula1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_quota_history_cell_lte.formula1
     *
     * @param formula1 the value for unicom_quota_history_cell_lte.formula1
     *
     * @mbggenerated
     */
    public void setFormula1(String formula1) {
        this.formula1 = formula1 == null ? null : formula1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_quota_history_cell_lte.formula2
     *
     * @return the value of unicom_quota_history_cell_lte.formula2
     *
     * @mbggenerated
     */
    public String getFormula2() {
        return formula2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_quota_history_cell_lte.formula2
     *
     * @param formula2 the value for unicom_quota_history_cell_lte.formula2
     *
     * @mbggenerated
     */
    public void setFormula2(String formula2) {
        this.formula2 = formula2 == null ? null : formula2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_quota_history_cell_lte.formula3
     *
     * @return the value of unicom_quota_history_cell_lte.formula3
     *
     * @mbggenerated
     */
    public String getFormula3() {
        return formula3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_quota_history_cell_lte.formula3
     *
     * @param formula3 the value for unicom_quota_history_cell_lte.formula3
     *
     * @mbggenerated
     */
    public void setFormula3(String formula3) {
        this.formula3 = formula3 == null ? null : formula3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_quota_history_cell_lte.formula4
     *
     * @return the value of unicom_quota_history_cell_lte.formula4
     *
     * @mbggenerated
     */
    public String getFormula4() {
        return formula4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_quota_history_cell_lte.formula4
     *
     * @param formula4 the value for unicom_quota_history_cell_lte.formula4
     *
     * @mbggenerated
     */
    public void setFormula4(String formula4) {
        this.formula4 = formula4 == null ? null : formula4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_quota_history_cell_lte.formula5
     *
     * @return the value of unicom_quota_history_cell_lte.formula5
     *
     * @mbggenerated
     */
    public String getFormula5() {
        return formula5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_quota_history_cell_lte.formula5
     *
     * @param formula5 the value for unicom_quota_history_cell_lte.formula5
     *
     * @mbggenerated
     */
    public void setFormula5(String formula5) {
        this.formula5 = formula5 == null ? null : formula5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_quota_history_cell_lte.formula6
     *
     * @return the value of unicom_quota_history_cell_lte.formula6
     *
     * @mbggenerated
     */
    public String getFormula6() {
        return formula6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_quota_history_cell_lte.formula6
     *
     * @param formula6 the value for unicom_quota_history_cell_lte.formula6
     *
     * @mbggenerated
     */
    public void setFormula6(String formula6) {
        this.formula6 = formula6 == null ? null : formula6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_quota_history_cell_lte.formula7
     *
     * @return the value of unicom_quota_history_cell_lte.formula7
     *
     * @mbggenerated
     */
    public String getFormula7() {
        return formula7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_quota_history_cell_lte.formula7
     *
     * @param formula7 the value for unicom_quota_history_cell_lte.formula7
     *
     * @mbggenerated
     */
    public void setFormula7(String formula7) {
        this.formula7 = formula7 == null ? null : formula7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_quota_history_cell_lte.formula8
     *
     * @return the value of unicom_quota_history_cell_lte.formula8
     *
     * @mbggenerated
     */
    public String getFormula8() {
        return formula8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_quota_history_cell_lte.formula8
     *
     * @param formula8 the value for unicom_quota_history_cell_lte.formula8
     *
     * @mbggenerated
     */
    public void setFormula8(String formula8) {
        this.formula8 = formula8 == null ? null : formula8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_quota_history_cell_lte.formula9
     *
     * @return the value of unicom_quota_history_cell_lte.formula9
     *
     * @mbggenerated
     */
    public String getFormula9() {
        return formula9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_quota_history_cell_lte.formula9
     *
     * @param formula9 the value for unicom_quota_history_cell_lte.formula9
     *
     * @mbggenerated
     */
    public void setFormula9(String formula9) {
        this.formula9 = formula9 == null ? null : formula9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_quota_history_cell_lte.formula10
     *
     * @return the value of unicom_quota_history_cell_lte.formula10
     *
     * @mbggenerated
     */
    public String getFormula10() {
        return formula10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_quota_history_cell_lte.formula10
     *
     * @param formula10 the value for unicom_quota_history_cell_lte.formula10
     *
     * @mbggenerated
     */
    public void setFormula10(String formula10) {
        this.formula10 = formula10 == null ? null : formula10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_quota_history_cell_lte.formula11
     *
     * @return the value of unicom_quota_history_cell_lte.formula11
     *
     * @mbggenerated
     */
    public String getFormula11() {
        return formula11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_quota_history_cell_lte.formula11
     *
     * @param formula11 the value for unicom_quota_history_cell_lte.formula11
     *
     * @mbggenerated
     */
    public void setFormula11(String formula11) {
        this.formula11 = formula11 == null ? null : formula11.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_quota_history_cell_lte.formula12
     *
     * @return the value of unicom_quota_history_cell_lte.formula12
     *
     * @mbggenerated
     */
    public String getFormula12() {
        return formula12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_quota_history_cell_lte.formula12
     *
     * @param formula12 the value for unicom_quota_history_cell_lte.formula12
     *
     * @mbggenerated
     */
    public void setFormula12(String formula12) {
        this.formula12 = formula12 == null ? null : formula12.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_quota_history_cell_lte.formula13
     *
     * @return the value of unicom_quota_history_cell_lte.formula13
     *
     * @mbggenerated
     */
    public String getFormula13() {
        return formula13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_quota_history_cell_lte.formula13
     *
     * @param formula13 the value for unicom_quota_history_cell_lte.formula13
     *
     * @mbggenerated
     */
    public void setFormula13(String formula13) {
        this.formula13 = formula13 == null ? null : formula13.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_quota_history_cell_lte.formula14
     *
     * @return the value of unicom_quota_history_cell_lte.formula14
     *
     * @mbggenerated
     */
    public String getFormula14() {
        return formula14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_quota_history_cell_lte.formula14
     *
     * @param formula14 the value for unicom_quota_history_cell_lte.formula14
     *
     * @mbggenerated
     */
    public void setFormula14(String formula14) {
        this.formula14 = formula14 == null ? null : formula14.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_quota_history_cell_lte.formula15
     *
     * @return the value of unicom_quota_history_cell_lte.formula15
     *
     * @mbggenerated
     */
    public String getFormula15() {
        return formula15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_quota_history_cell_lte.formula15
     *
     * @param formula15 the value for unicom_quota_history_cell_lte.formula15
     *
     * @mbggenerated
     */
    public void setFormula15(String formula15) {
        this.formula15 = formula15 == null ? null : formula15.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_quota_history_cell_lte.formula16
     *
     * @return the value of unicom_quota_history_cell_lte.formula16
     *
     * @mbggenerated
     */
    public String getFormula16() {
        return formula16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_quota_history_cell_lte.formula16
     *
     * @param formula16 the value for unicom_quota_history_cell_lte.formula16
     *
     * @mbggenerated
     */
    public void setFormula16(String formula16) {
        this.formula16 = formula16 == null ? null : formula16.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_quota_history_cell_lte.formula17
     *
     * @return the value of unicom_quota_history_cell_lte.formula17
     *
     * @mbggenerated
     */
    public String getFormula17() {
        return formula17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_quota_history_cell_lte.formula17
     *
     * @param formula17 the value for unicom_quota_history_cell_lte.formula17
     *
     * @mbggenerated
     */
    public void setFormula17(String formula17) {
        this.formula17 = formula17 == null ? null : formula17.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_quota_history_cell_lte.formula18
     *
     * @return the value of unicom_quota_history_cell_lte.formula18
     *
     * @mbggenerated
     */
    public String getFormula18() {
        return formula18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_quota_history_cell_lte.formula18
     *
     * @param formula18 the value for unicom_quota_history_cell_lte.formula18
     *
     * @mbggenerated
     */
    public void setFormula18(String formula18) {
        this.formula18 = formula18 == null ? null : formula18.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_quota_history_cell_lte.formula19
     *
     * @return the value of unicom_quota_history_cell_lte.formula19
     *
     * @mbggenerated
     */
    public String getFormula19() {
        return formula19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_quota_history_cell_lte.formula19
     *
     * @param formula19 the value for unicom_quota_history_cell_lte.formula19
     *
     * @mbggenerated
     */
    public void setFormula19(String formula19) {
        this.formula19 = formula19 == null ? null : formula19.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_quota_history_cell_lte.formula20
     *
     * @return the value of unicom_quota_history_cell_lte.formula20
     *
     * @mbggenerated
     */
    public String getFormula20() {
        return formula20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_quota_history_cell_lte.formula20
     *
     * @param formula20 the value for unicom_quota_history_cell_lte.formula20
     *
     * @mbggenerated
     */
    public void setFormula20(String formula20) {
        this.formula20 = formula20 == null ? null : formula20.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_quota_history_cell_lte.formula21
     *
     * @return the value of unicom_quota_history_cell_lte.formula21
     *
     * @mbggenerated
     */
    public String getFormula21() {
        return formula21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_quota_history_cell_lte.formula21
     *
     * @param formula21 the value for unicom_quota_history_cell_lte.formula21
     *
     * @mbggenerated
     */
    public void setFormula21(String formula21) {
        this.formula21 = formula21 == null ? null : formula21.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_quota_history_cell_lte.formula22
     *
     * @return the value of unicom_quota_history_cell_lte.formula22
     *
     * @mbggenerated
     */
    public String getFormula22() {
        return formula22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_quota_history_cell_lte.formula22
     *
     * @param formula22 the value for unicom_quota_history_cell_lte.formula22
     *
     * @mbggenerated
     */
    public void setFormula22(String formula22) {
        this.formula22 = formula22 == null ? null : formula22.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_quota_history_cell_lte.formula23
     *
     * @return the value of unicom_quota_history_cell_lte.formula23
     *
     * @mbggenerated
     */
    public String getFormula23() {
        return formula23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_quota_history_cell_lte.formula23
     *
     * @param formula23 the value for unicom_quota_history_cell_lte.formula23
     *
     * @mbggenerated
     */
    public void setFormula23(String formula23) {
        this.formula23 = formula23 == null ? null : formula23.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_quota_history_cell_lte.formula24
     *
     * @return the value of unicom_quota_history_cell_lte.formula24
     *
     * @mbggenerated
     */
    public String getFormula24() {
        return formula24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_quota_history_cell_lte.formula24
     *
     * @param formula24 the value for unicom_quota_history_cell_lte.formula24
     *
     * @mbggenerated
     */
    public void setFormula24(String formula24) {
        this.formula24 = formula24 == null ? null : formula24.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_quota_history_cell_lte.formula25
     *
     * @return the value of unicom_quota_history_cell_lte.formula25
     *
     * @mbggenerated
     */
    public String getFormula25() {
        return formula25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_quota_history_cell_lte.formula25
     *
     * @param formula25 the value for unicom_quota_history_cell_lte.formula25
     *
     * @mbggenerated
     */
    public void setFormula25(String formula25) {
        this.formula25 = formula25 == null ? null : formula25.trim();
    }
}