package com.hongshen.sran_service.entity;

import java.io.Serializable;
import java.util.Date;

public class UnicomUserTaskGroupWcdma implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_user_task_group_wcdma.login_name
     *
     * @mbggenerated
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_user_task_group_wcdma.isUseScript
     *
     * @mbggenerated
     */
    private Boolean isusescript;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_user_task_group_wcdma.startTime
     *
     * @mbggenerated
     */
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_user_task_group_wcdma.endTime
     *
     * @mbggenerated
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table unicom_user_task_group_wcdma
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_user_task_group_wcdma.login_name
     *
     * @return the value of unicom_user_task_group_wcdma.login_name
     *
     * @mbggenerated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_user_task_group_wcdma.login_name
     *
     * @param loginName the value for unicom_user_task_group_wcdma.login_name
     *
     * @mbggenerated
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_user_task_group_wcdma.isUseScript
     *
     * @return the value of unicom_user_task_group_wcdma.isUseScript
     *
     * @mbggenerated
     */
    public Boolean getIsusescript() {
        return isusescript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_user_task_group_wcdma.isUseScript
     *
     * @param isusescript the value for unicom_user_task_group_wcdma.isUseScript
     *
     * @mbggenerated
     */
    public void setIsusescript(Boolean isusescript) {
        this.isusescript = isusescript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_user_task_group_wcdma.startTime
     *
     * @return the value of unicom_user_task_group_wcdma.startTime
     *
     * @mbggenerated
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_user_task_group_wcdma.startTime
     *
     * @param starttime the value for unicom_user_task_group_wcdma.startTime
     *
     * @mbggenerated
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_user_task_group_wcdma.endTime
     *
     * @return the value of unicom_user_task_group_wcdma.endTime
     *
     * @mbggenerated
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_user_task_group_wcdma.endTime
     *
     * @param endtime the value for unicom_user_task_group_wcdma.endTime
     *
     * @mbggenerated
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }
}