package com.hongshen.sran_service.entity;

import java.io.Serializable;
import java.util.Date;

public class UnicomCounterHistoryWcdma implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_wcdma.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_wcdma.time
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_wcdma.pmNoIuSigEstablishSuccessCs
     *
     * @mbggenerated
     */
    private String pmnoiusigestablishsuccesscs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_wcdma.pmNoIuSigEstablishAttemptCs
     *
     * @mbggenerated
     */
    private String pmnoiusigestablishattemptcs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_wcdma.pmNoIuSigEstablishSuccessPs
     *
     * @mbggenerated
     */
    private String pmnoiusigestablishsuccessps;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_wcdma.pmNoIuSigEstablishAttemptPs
     *
     * @mbggenerated
     */
    private String pmnoiusigestablishattemptps;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_wcdma.pmTotNoRrcConnectReqSuccess
     *
     * @mbggenerated
     */
    private String pmtotnorrcconnectreqsuccess;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_wcdma.pmTotNoRrcConnectReq
     *
     * @mbggenerated
     */
    private String pmtotnorrcconnectreq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_wcdma.pmNoLoadSharingRrcConn
     *
     * @mbggenerated
     */
    private String pmnoloadsharingrrcconn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_wcdma.pmNoRejRrcConnSpFlowCtrl
     *
     * @mbggenerated
     */
    private String pmnorejrrcconnspflowctrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_wcdma.pmTotNoRrcConnectReqPsSucc
     *
     * @mbggenerated
     */
    private String pmtotnorrcconnectreqpssucc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_wcdma.pmTotNoRrcConnectReqPs
     *
     * @mbggenerated
     */
    private String pmtotnorrcconnectreqps;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_wcdma.pmNoLoadSharingRrcConnPs
     *
     * @mbggenerated
     */
    private String pmnoloadsharingrrcconnps;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_wcdma.pmTotNoRrcConnectReqCsSucc
     *
     * @mbggenerated
     */
    private String pmtotnorrcconnectreqcssucc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_wcdma.pmTotNoRrcConnectReqCs
     *
     * @mbggenerated
     */
    private String pmtotnorrcconnectreqcs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_wcdma.pmNoLoadSharingRrcConnCs
     *
     * @mbggenerated
     */
    private String pmnoloadsharingrrcconncs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_wcdma.pmNoRabEstablishSuccessSpeech
     *
     * @mbggenerated
     */
    private String pmnorabestablishsuccessspeech;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_wcdma.pmNoRabEstablishAttemptSpeech
     *
     * @mbggenerated
     */
    private String pmnorabestablishattemptspeech;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_wcdma.pmNoRabEstablishSuccessPacketInteractive
     *
     * @mbggenerated
     */
    private String pmnorabestablishsuccesspacketinteractive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_wcdma.pmNoRabEstablishAttemptPacketInteractive
     *
     * @mbggenerated
     */
    private String pmnorabestablishattemptpacketinteractive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_wcdma.pmNoTimesRlAddToActSet
     *
     * @mbggenerated
     */
    private String pmnotimesrladdtoactset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_wcdma.pmNoTimesCellFailAddToActSet
     *
     * @mbggenerated
     */
    private String pmnotimescellfailaddtoactset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_wcdma.pmNoSystemRabReleaseSpeech
     *
     * @mbggenerated
     */
    private String pmnosystemrabreleasespeech;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_wcdma.pmNoNormalRabReleaseSpeech
     *
     * @mbggenerated
     */
    private String pmnonormalrabreleasespeech;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_wcdma.pmNoSystemRabReleasePacket
     *
     * @mbggenerated
     */
    private String pmnosystemrabreleasepacket;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_wcdma.pmNoSystemRabReleasePacketUra
     *
     * @mbggenerated
     */
    private String pmnosystemrabreleasepacketura;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_wcdma.pmChSwitchAttemptFachUra
     *
     * @mbggenerated
     */
    private String pmchswitchattemptfachura;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_wcdma.pmChSwitchSuccFachUra
     *
     * @mbggenerated
     */
    private String pmchswitchsuccfachura;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_wcdma.pmChSwitchAttemptDchUra
     *
     * @mbggenerated
     */
    private String pmchswitchattemptdchura;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_wcdma.pmChSwitchSuccDchUra
     *
     * @mbggenerated
     */
    private String pmchswitchsuccdchura;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_wcdma.pmChSwitchAttemptHsUra
     *
     * @mbggenerated
     */
    private String pmchswitchattempthsura;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_wcdma.pmChSwitchSuccHsUra
     *
     * @mbggenerated
     */
    private String pmchswitchsucchsura;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_wcdma.pmNoNormalRabReleasePacket
     *
     * @mbggenerated
     */
    private String pmnonormalrabreleasepacket;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_wcdma.pmNoNormalRabReleasePacketUra
     *
     * @mbggenerated
     */
    private String pmnonormalrabreleasepacketura;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table unicom_counter_history_wcdma
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_wcdma.name
     *
     * @return the value of unicom_counter_history_wcdma.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_wcdma.name
     *
     * @param name the value for unicom_counter_history_wcdma.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_wcdma.time
     *
     * @return the value of unicom_counter_history_wcdma.time
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_wcdma.time
     *
     * @param time the value for unicom_counter_history_wcdma.time
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_wcdma.pmNoIuSigEstablishSuccessCs
     *
     * @return the value of unicom_counter_history_wcdma.pmNoIuSigEstablishSuccessCs
     *
     * @mbggenerated
     */
    public String getPmnoiusigestablishsuccesscs() {
        return pmnoiusigestablishsuccesscs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_wcdma.pmNoIuSigEstablishSuccessCs
     *
     * @param pmnoiusigestablishsuccesscs the value for unicom_counter_history_wcdma.pmNoIuSigEstablishSuccessCs
     *
     * @mbggenerated
     */
    public void setPmnoiusigestablishsuccesscs(String pmnoiusigestablishsuccesscs) {
        this.pmnoiusigestablishsuccesscs = pmnoiusigestablishsuccesscs == null ? null : pmnoiusigestablishsuccesscs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_wcdma.pmNoIuSigEstablishAttemptCs
     *
     * @return the value of unicom_counter_history_wcdma.pmNoIuSigEstablishAttemptCs
     *
     * @mbggenerated
     */
    public String getPmnoiusigestablishattemptcs() {
        return pmnoiusigestablishattemptcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_wcdma.pmNoIuSigEstablishAttemptCs
     *
     * @param pmnoiusigestablishattemptcs the value for unicom_counter_history_wcdma.pmNoIuSigEstablishAttemptCs
     *
     * @mbggenerated
     */
    public void setPmnoiusigestablishattemptcs(String pmnoiusigestablishattemptcs) {
        this.pmnoiusigestablishattemptcs = pmnoiusigestablishattemptcs == null ? null : pmnoiusigestablishattemptcs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_wcdma.pmNoIuSigEstablishSuccessPs
     *
     * @return the value of unicom_counter_history_wcdma.pmNoIuSigEstablishSuccessPs
     *
     * @mbggenerated
     */
    public String getPmnoiusigestablishsuccessps() {
        return pmnoiusigestablishsuccessps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_wcdma.pmNoIuSigEstablishSuccessPs
     *
     * @param pmnoiusigestablishsuccessps the value for unicom_counter_history_wcdma.pmNoIuSigEstablishSuccessPs
     *
     * @mbggenerated
     */
    public void setPmnoiusigestablishsuccessps(String pmnoiusigestablishsuccessps) {
        this.pmnoiusigestablishsuccessps = pmnoiusigestablishsuccessps == null ? null : pmnoiusigestablishsuccessps.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_wcdma.pmNoIuSigEstablishAttemptPs
     *
     * @return the value of unicom_counter_history_wcdma.pmNoIuSigEstablishAttemptPs
     *
     * @mbggenerated
     */
    public String getPmnoiusigestablishattemptps() {
        return pmnoiusigestablishattemptps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_wcdma.pmNoIuSigEstablishAttemptPs
     *
     * @param pmnoiusigestablishattemptps the value for unicom_counter_history_wcdma.pmNoIuSigEstablishAttemptPs
     *
     * @mbggenerated
     */
    public void setPmnoiusigestablishattemptps(String pmnoiusigestablishattemptps) {
        this.pmnoiusigestablishattemptps = pmnoiusigestablishattemptps == null ? null : pmnoiusigestablishattemptps.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_wcdma.pmTotNoRrcConnectReqSuccess
     *
     * @return the value of unicom_counter_history_wcdma.pmTotNoRrcConnectReqSuccess
     *
     * @mbggenerated
     */
    public String getPmtotnorrcconnectreqsuccess() {
        return pmtotnorrcconnectreqsuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_wcdma.pmTotNoRrcConnectReqSuccess
     *
     * @param pmtotnorrcconnectreqsuccess the value for unicom_counter_history_wcdma.pmTotNoRrcConnectReqSuccess
     *
     * @mbggenerated
     */
    public void setPmtotnorrcconnectreqsuccess(String pmtotnorrcconnectreqsuccess) {
        this.pmtotnorrcconnectreqsuccess = pmtotnorrcconnectreqsuccess == null ? null : pmtotnorrcconnectreqsuccess.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_wcdma.pmTotNoRrcConnectReq
     *
     * @return the value of unicom_counter_history_wcdma.pmTotNoRrcConnectReq
     *
     * @mbggenerated
     */
    public String getPmtotnorrcconnectreq() {
        return pmtotnorrcconnectreq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_wcdma.pmTotNoRrcConnectReq
     *
     * @param pmtotnorrcconnectreq the value for unicom_counter_history_wcdma.pmTotNoRrcConnectReq
     *
     * @mbggenerated
     */
    public void setPmtotnorrcconnectreq(String pmtotnorrcconnectreq) {
        this.pmtotnorrcconnectreq = pmtotnorrcconnectreq == null ? null : pmtotnorrcconnectreq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_wcdma.pmNoLoadSharingRrcConn
     *
     * @return the value of unicom_counter_history_wcdma.pmNoLoadSharingRrcConn
     *
     * @mbggenerated
     */
    public String getPmnoloadsharingrrcconn() {
        return pmnoloadsharingrrcconn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_wcdma.pmNoLoadSharingRrcConn
     *
     * @param pmnoloadsharingrrcconn the value for unicom_counter_history_wcdma.pmNoLoadSharingRrcConn
     *
     * @mbggenerated
     */
    public void setPmnoloadsharingrrcconn(String pmnoloadsharingrrcconn) {
        this.pmnoloadsharingrrcconn = pmnoloadsharingrrcconn == null ? null : pmnoloadsharingrrcconn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_wcdma.pmNoRejRrcConnSpFlowCtrl
     *
     * @return the value of unicom_counter_history_wcdma.pmNoRejRrcConnSpFlowCtrl
     *
     * @mbggenerated
     */
    public String getPmnorejrrcconnspflowctrl() {
        return pmnorejrrcconnspflowctrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_wcdma.pmNoRejRrcConnSpFlowCtrl
     *
     * @param pmnorejrrcconnspflowctrl the value for unicom_counter_history_wcdma.pmNoRejRrcConnSpFlowCtrl
     *
     * @mbggenerated
     */
    public void setPmnorejrrcconnspflowctrl(String pmnorejrrcconnspflowctrl) {
        this.pmnorejrrcconnspflowctrl = pmnorejrrcconnspflowctrl == null ? null : pmnorejrrcconnspflowctrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_wcdma.pmTotNoRrcConnectReqPsSucc
     *
     * @return the value of unicom_counter_history_wcdma.pmTotNoRrcConnectReqPsSucc
     *
     * @mbggenerated
     */
    public String getPmtotnorrcconnectreqpssucc() {
        return pmtotnorrcconnectreqpssucc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_wcdma.pmTotNoRrcConnectReqPsSucc
     *
     * @param pmtotnorrcconnectreqpssucc the value for unicom_counter_history_wcdma.pmTotNoRrcConnectReqPsSucc
     *
     * @mbggenerated
     */
    public void setPmtotnorrcconnectreqpssucc(String pmtotnorrcconnectreqpssucc) {
        this.pmtotnorrcconnectreqpssucc = pmtotnorrcconnectreqpssucc == null ? null : pmtotnorrcconnectreqpssucc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_wcdma.pmTotNoRrcConnectReqPs
     *
     * @return the value of unicom_counter_history_wcdma.pmTotNoRrcConnectReqPs
     *
     * @mbggenerated
     */
    public String getPmtotnorrcconnectreqps() {
        return pmtotnorrcconnectreqps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_wcdma.pmTotNoRrcConnectReqPs
     *
     * @param pmtotnorrcconnectreqps the value for unicom_counter_history_wcdma.pmTotNoRrcConnectReqPs
     *
     * @mbggenerated
     */
    public void setPmtotnorrcconnectreqps(String pmtotnorrcconnectreqps) {
        this.pmtotnorrcconnectreqps = pmtotnorrcconnectreqps == null ? null : pmtotnorrcconnectreqps.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_wcdma.pmNoLoadSharingRrcConnPs
     *
     * @return the value of unicom_counter_history_wcdma.pmNoLoadSharingRrcConnPs
     *
     * @mbggenerated
     */
    public String getPmnoloadsharingrrcconnps() {
        return pmnoloadsharingrrcconnps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_wcdma.pmNoLoadSharingRrcConnPs
     *
     * @param pmnoloadsharingrrcconnps the value for unicom_counter_history_wcdma.pmNoLoadSharingRrcConnPs
     *
     * @mbggenerated
     */
    public void setPmnoloadsharingrrcconnps(String pmnoloadsharingrrcconnps) {
        this.pmnoloadsharingrrcconnps = pmnoloadsharingrrcconnps == null ? null : pmnoloadsharingrrcconnps.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_wcdma.pmTotNoRrcConnectReqCsSucc
     *
     * @return the value of unicom_counter_history_wcdma.pmTotNoRrcConnectReqCsSucc
     *
     * @mbggenerated
     */
    public String getPmtotnorrcconnectreqcssucc() {
        return pmtotnorrcconnectreqcssucc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_wcdma.pmTotNoRrcConnectReqCsSucc
     *
     * @param pmtotnorrcconnectreqcssucc the value for unicom_counter_history_wcdma.pmTotNoRrcConnectReqCsSucc
     *
     * @mbggenerated
     */
    public void setPmtotnorrcconnectreqcssucc(String pmtotnorrcconnectreqcssucc) {
        this.pmtotnorrcconnectreqcssucc = pmtotnorrcconnectreqcssucc == null ? null : pmtotnorrcconnectreqcssucc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_wcdma.pmTotNoRrcConnectReqCs
     *
     * @return the value of unicom_counter_history_wcdma.pmTotNoRrcConnectReqCs
     *
     * @mbggenerated
     */
    public String getPmtotnorrcconnectreqcs() {
        return pmtotnorrcconnectreqcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_wcdma.pmTotNoRrcConnectReqCs
     *
     * @param pmtotnorrcconnectreqcs the value for unicom_counter_history_wcdma.pmTotNoRrcConnectReqCs
     *
     * @mbggenerated
     */
    public void setPmtotnorrcconnectreqcs(String pmtotnorrcconnectreqcs) {
        this.pmtotnorrcconnectreqcs = pmtotnorrcconnectreqcs == null ? null : pmtotnorrcconnectreqcs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_wcdma.pmNoLoadSharingRrcConnCs
     *
     * @return the value of unicom_counter_history_wcdma.pmNoLoadSharingRrcConnCs
     *
     * @mbggenerated
     */
    public String getPmnoloadsharingrrcconncs() {
        return pmnoloadsharingrrcconncs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_wcdma.pmNoLoadSharingRrcConnCs
     *
     * @param pmnoloadsharingrrcconncs the value for unicom_counter_history_wcdma.pmNoLoadSharingRrcConnCs
     *
     * @mbggenerated
     */
    public void setPmnoloadsharingrrcconncs(String pmnoloadsharingrrcconncs) {
        this.pmnoloadsharingrrcconncs = pmnoloadsharingrrcconncs == null ? null : pmnoloadsharingrrcconncs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_wcdma.pmNoRabEstablishSuccessSpeech
     *
     * @return the value of unicom_counter_history_wcdma.pmNoRabEstablishSuccessSpeech
     *
     * @mbggenerated
     */
    public String getPmnorabestablishsuccessspeech() {
        return pmnorabestablishsuccessspeech;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_wcdma.pmNoRabEstablishSuccessSpeech
     *
     * @param pmnorabestablishsuccessspeech the value for unicom_counter_history_wcdma.pmNoRabEstablishSuccessSpeech
     *
     * @mbggenerated
     */
    public void setPmnorabestablishsuccessspeech(String pmnorabestablishsuccessspeech) {
        this.pmnorabestablishsuccessspeech = pmnorabestablishsuccessspeech == null ? null : pmnorabestablishsuccessspeech.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_wcdma.pmNoRabEstablishAttemptSpeech
     *
     * @return the value of unicom_counter_history_wcdma.pmNoRabEstablishAttemptSpeech
     *
     * @mbggenerated
     */
    public String getPmnorabestablishattemptspeech() {
        return pmnorabestablishattemptspeech;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_wcdma.pmNoRabEstablishAttemptSpeech
     *
     * @param pmnorabestablishattemptspeech the value for unicom_counter_history_wcdma.pmNoRabEstablishAttemptSpeech
     *
     * @mbggenerated
     */
    public void setPmnorabestablishattemptspeech(String pmnorabestablishattemptspeech) {
        this.pmnorabestablishattemptspeech = pmnorabestablishattemptspeech == null ? null : pmnorabestablishattemptspeech.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_wcdma.pmNoRabEstablishSuccessPacketInteractive
     *
     * @return the value of unicom_counter_history_wcdma.pmNoRabEstablishSuccessPacketInteractive
     *
     * @mbggenerated
     */
    public String getPmnorabestablishsuccesspacketinteractive() {
        return pmnorabestablishsuccesspacketinteractive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_wcdma.pmNoRabEstablishSuccessPacketInteractive
     *
     * @param pmnorabestablishsuccesspacketinteractive the value for unicom_counter_history_wcdma.pmNoRabEstablishSuccessPacketInteractive
     *
     * @mbggenerated
     */
    public void setPmnorabestablishsuccesspacketinteractive(String pmnorabestablishsuccesspacketinteractive) {
        this.pmnorabestablishsuccesspacketinteractive = pmnorabestablishsuccesspacketinteractive == null ? null : pmnorabestablishsuccesspacketinteractive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_wcdma.pmNoRabEstablishAttemptPacketInteractive
     *
     * @return the value of unicom_counter_history_wcdma.pmNoRabEstablishAttemptPacketInteractive
     *
     * @mbggenerated
     */
    public String getPmnorabestablishattemptpacketinteractive() {
        return pmnorabestablishattemptpacketinteractive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_wcdma.pmNoRabEstablishAttemptPacketInteractive
     *
     * @param pmnorabestablishattemptpacketinteractive the value for unicom_counter_history_wcdma.pmNoRabEstablishAttemptPacketInteractive
     *
     * @mbggenerated
     */
    public void setPmnorabestablishattemptpacketinteractive(String pmnorabestablishattemptpacketinteractive) {
        this.pmnorabestablishattemptpacketinteractive = pmnorabestablishattemptpacketinteractive == null ? null : pmnorabestablishattemptpacketinteractive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_wcdma.pmNoTimesRlAddToActSet
     *
     * @return the value of unicom_counter_history_wcdma.pmNoTimesRlAddToActSet
     *
     * @mbggenerated
     */
    public String getPmnotimesrladdtoactset() {
        return pmnotimesrladdtoactset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_wcdma.pmNoTimesRlAddToActSet
     *
     * @param pmnotimesrladdtoactset the value for unicom_counter_history_wcdma.pmNoTimesRlAddToActSet
     *
     * @mbggenerated
     */
    public void setPmnotimesrladdtoactset(String pmnotimesrladdtoactset) {
        this.pmnotimesrladdtoactset = pmnotimesrladdtoactset == null ? null : pmnotimesrladdtoactset.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_wcdma.pmNoTimesCellFailAddToActSet
     *
     * @return the value of unicom_counter_history_wcdma.pmNoTimesCellFailAddToActSet
     *
     * @mbggenerated
     */
    public String getPmnotimescellfailaddtoactset() {
        return pmnotimescellfailaddtoactset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_wcdma.pmNoTimesCellFailAddToActSet
     *
     * @param pmnotimescellfailaddtoactset the value for unicom_counter_history_wcdma.pmNoTimesCellFailAddToActSet
     *
     * @mbggenerated
     */
    public void setPmnotimescellfailaddtoactset(String pmnotimescellfailaddtoactset) {
        this.pmnotimescellfailaddtoactset = pmnotimescellfailaddtoactset == null ? null : pmnotimescellfailaddtoactset.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_wcdma.pmNoSystemRabReleaseSpeech
     *
     * @return the value of unicom_counter_history_wcdma.pmNoSystemRabReleaseSpeech
     *
     * @mbggenerated
     */
    public String getPmnosystemrabreleasespeech() {
        return pmnosystemrabreleasespeech;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_wcdma.pmNoSystemRabReleaseSpeech
     *
     * @param pmnosystemrabreleasespeech the value for unicom_counter_history_wcdma.pmNoSystemRabReleaseSpeech
     *
     * @mbggenerated
     */
    public void setPmnosystemrabreleasespeech(String pmnosystemrabreleasespeech) {
        this.pmnosystemrabreleasespeech = pmnosystemrabreleasespeech == null ? null : pmnosystemrabreleasespeech.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_wcdma.pmNoNormalRabReleaseSpeech
     *
     * @return the value of unicom_counter_history_wcdma.pmNoNormalRabReleaseSpeech
     *
     * @mbggenerated
     */
    public String getPmnonormalrabreleasespeech() {
        return pmnonormalrabreleasespeech;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_wcdma.pmNoNormalRabReleaseSpeech
     *
     * @param pmnonormalrabreleasespeech the value for unicom_counter_history_wcdma.pmNoNormalRabReleaseSpeech
     *
     * @mbggenerated
     */
    public void setPmnonormalrabreleasespeech(String pmnonormalrabreleasespeech) {
        this.pmnonormalrabreleasespeech = pmnonormalrabreleasespeech == null ? null : pmnonormalrabreleasespeech.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_wcdma.pmNoSystemRabReleasePacket
     *
     * @return the value of unicom_counter_history_wcdma.pmNoSystemRabReleasePacket
     *
     * @mbggenerated
     */
    public String getPmnosystemrabreleasepacket() {
        return pmnosystemrabreleasepacket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_wcdma.pmNoSystemRabReleasePacket
     *
     * @param pmnosystemrabreleasepacket the value for unicom_counter_history_wcdma.pmNoSystemRabReleasePacket
     *
     * @mbggenerated
     */
    public void setPmnosystemrabreleasepacket(String pmnosystemrabreleasepacket) {
        this.pmnosystemrabreleasepacket = pmnosystemrabreleasepacket == null ? null : pmnosystemrabreleasepacket.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_wcdma.pmNoSystemRabReleasePacketUra
     *
     * @return the value of unicom_counter_history_wcdma.pmNoSystemRabReleasePacketUra
     *
     * @mbggenerated
     */
    public String getPmnosystemrabreleasepacketura() {
        return pmnosystemrabreleasepacketura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_wcdma.pmNoSystemRabReleasePacketUra
     *
     * @param pmnosystemrabreleasepacketura the value for unicom_counter_history_wcdma.pmNoSystemRabReleasePacketUra
     *
     * @mbggenerated
     */
    public void setPmnosystemrabreleasepacketura(String pmnosystemrabreleasepacketura) {
        this.pmnosystemrabreleasepacketura = pmnosystemrabreleasepacketura == null ? null : pmnosystemrabreleasepacketura.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_wcdma.pmChSwitchAttemptFachUra
     *
     * @return the value of unicom_counter_history_wcdma.pmChSwitchAttemptFachUra
     *
     * @mbggenerated
     */
    public String getPmchswitchattemptfachura() {
        return pmchswitchattemptfachura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_wcdma.pmChSwitchAttemptFachUra
     *
     * @param pmchswitchattemptfachura the value for unicom_counter_history_wcdma.pmChSwitchAttemptFachUra
     *
     * @mbggenerated
     */
    public void setPmchswitchattemptfachura(String pmchswitchattemptfachura) {
        this.pmchswitchattemptfachura = pmchswitchattemptfachura == null ? null : pmchswitchattemptfachura.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_wcdma.pmChSwitchSuccFachUra
     *
     * @return the value of unicom_counter_history_wcdma.pmChSwitchSuccFachUra
     *
     * @mbggenerated
     */
    public String getPmchswitchsuccfachura() {
        return pmchswitchsuccfachura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_wcdma.pmChSwitchSuccFachUra
     *
     * @param pmchswitchsuccfachura the value for unicom_counter_history_wcdma.pmChSwitchSuccFachUra
     *
     * @mbggenerated
     */
    public void setPmchswitchsuccfachura(String pmchswitchsuccfachura) {
        this.pmchswitchsuccfachura = pmchswitchsuccfachura == null ? null : pmchswitchsuccfachura.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_wcdma.pmChSwitchAttemptDchUra
     *
     * @return the value of unicom_counter_history_wcdma.pmChSwitchAttemptDchUra
     *
     * @mbggenerated
     */
    public String getPmchswitchattemptdchura() {
        return pmchswitchattemptdchura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_wcdma.pmChSwitchAttemptDchUra
     *
     * @param pmchswitchattemptdchura the value for unicom_counter_history_wcdma.pmChSwitchAttemptDchUra
     *
     * @mbggenerated
     */
    public void setPmchswitchattemptdchura(String pmchswitchattemptdchura) {
        this.pmchswitchattemptdchura = pmchswitchattemptdchura == null ? null : pmchswitchattemptdchura.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_wcdma.pmChSwitchSuccDchUra
     *
     * @return the value of unicom_counter_history_wcdma.pmChSwitchSuccDchUra
     *
     * @mbggenerated
     */
    public String getPmchswitchsuccdchura() {
        return pmchswitchsuccdchura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_wcdma.pmChSwitchSuccDchUra
     *
     * @param pmchswitchsuccdchura the value for unicom_counter_history_wcdma.pmChSwitchSuccDchUra
     *
     * @mbggenerated
     */
    public void setPmchswitchsuccdchura(String pmchswitchsuccdchura) {
        this.pmchswitchsuccdchura = pmchswitchsuccdchura == null ? null : pmchswitchsuccdchura.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_wcdma.pmChSwitchAttemptHsUra
     *
     * @return the value of unicom_counter_history_wcdma.pmChSwitchAttemptHsUra
     *
     * @mbggenerated
     */
    public String getPmchswitchattempthsura() {
        return pmchswitchattempthsura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_wcdma.pmChSwitchAttemptHsUra
     *
     * @param pmchswitchattempthsura the value for unicom_counter_history_wcdma.pmChSwitchAttemptHsUra
     *
     * @mbggenerated
     */
    public void setPmchswitchattempthsura(String pmchswitchattempthsura) {
        this.pmchswitchattempthsura = pmchswitchattempthsura == null ? null : pmchswitchattempthsura.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_wcdma.pmChSwitchSuccHsUra
     *
     * @return the value of unicom_counter_history_wcdma.pmChSwitchSuccHsUra
     *
     * @mbggenerated
     */
    public String getPmchswitchsucchsura() {
        return pmchswitchsucchsura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_wcdma.pmChSwitchSuccHsUra
     *
     * @param pmchswitchsucchsura the value for unicom_counter_history_wcdma.pmChSwitchSuccHsUra
     *
     * @mbggenerated
     */
    public void setPmchswitchsucchsura(String pmchswitchsucchsura) {
        this.pmchswitchsucchsura = pmchswitchsucchsura == null ? null : pmchswitchsucchsura.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_wcdma.pmNoNormalRabReleasePacket
     *
     * @return the value of unicom_counter_history_wcdma.pmNoNormalRabReleasePacket
     *
     * @mbggenerated
     */
    public String getPmnonormalrabreleasepacket() {
        return pmnonormalrabreleasepacket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_wcdma.pmNoNormalRabReleasePacket
     *
     * @param pmnonormalrabreleasepacket the value for unicom_counter_history_wcdma.pmNoNormalRabReleasePacket
     *
     * @mbggenerated
     */
    public void setPmnonormalrabreleasepacket(String pmnonormalrabreleasepacket) {
        this.pmnonormalrabreleasepacket = pmnonormalrabreleasepacket == null ? null : pmnonormalrabreleasepacket.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_wcdma.pmNoNormalRabReleasePacketUra
     *
     * @return the value of unicom_counter_history_wcdma.pmNoNormalRabReleasePacketUra
     *
     * @mbggenerated
     */
    public String getPmnonormalrabreleasepacketura() {
        return pmnonormalrabreleasepacketura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_wcdma.pmNoNormalRabReleasePacketUra
     *
     * @param pmnonormalrabreleasepacketura the value for unicom_counter_history_wcdma.pmNoNormalRabReleasePacketUra
     *
     * @mbggenerated
     */
    public void setPmnonormalrabreleasepacketura(String pmnonormalrabreleasepacketura) {
        this.pmnonormalrabreleasepacketura = pmnonormalrabreleasepacketura == null ? null : pmnonormalrabreleasepacketura.trim();
    }
}