package com.hongshen.sran_service.entity;

import java.io.Serializable;
import java.util.Date;

public class UnicomAlarmWcdma implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_alarm_wcdma.node_name
     *
     * @mbggenerated
     */
    private String nodeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_alarm_wcdma.mo
     *
     * @mbggenerated
     */
    private String mo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_alarm_wcdma.alarm_time
     *
     * @mbggenerated
     */
    private Date alarmTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_alarm_wcdma.alarm_name_id
     *
     * @mbggenerated
     */
    private String alarmNameId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_alarm_wcdma.alarm_type_id
     *
     * @mbggenerated
     */
    private String alarmTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_alarm_wcdma.cell_name
     *
     * @mbggenerated
     */
    private String cellName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table unicom_alarm_wcdma
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_alarm_wcdma.node_name
     *
     * @return the value of unicom_alarm_wcdma.node_name
     *
     * @mbggenerated
     */
    public String getNodeName() {
        return nodeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_alarm_wcdma.node_name
     *
     * @param nodeName the value for unicom_alarm_wcdma.node_name
     *
     * @mbggenerated
     */
    public void setNodeName(String nodeName) {
        this.nodeName = nodeName == null ? null : nodeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_alarm_wcdma.mo
     *
     * @return the value of unicom_alarm_wcdma.mo
     *
     * @mbggenerated
     */
    public String getMo() {
        return mo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_alarm_wcdma.mo
     *
     * @param mo the value for unicom_alarm_wcdma.mo
     *
     * @mbggenerated
     */
    public void setMo(String mo) {
        this.mo = mo == null ? null : mo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_alarm_wcdma.alarm_time
     *
     * @return the value of unicom_alarm_wcdma.alarm_time
     *
     * @mbggenerated
     */
    public Date getAlarmTime() {
        return alarmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_alarm_wcdma.alarm_time
     *
     * @param alarmTime the value for unicom_alarm_wcdma.alarm_time
     *
     * @mbggenerated
     */
    public void setAlarmTime(Date alarmTime) {
        this.alarmTime = alarmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_alarm_wcdma.alarm_name_id
     *
     * @return the value of unicom_alarm_wcdma.alarm_name_id
     *
     * @mbggenerated
     */
    public String getAlarmNameId() {
        return alarmNameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_alarm_wcdma.alarm_name_id
     *
     * @param alarmNameId the value for unicom_alarm_wcdma.alarm_name_id
     *
     * @mbggenerated
     */
    public void setAlarmNameId(String alarmNameId) {
        this.alarmNameId = alarmNameId == null ? null : alarmNameId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_alarm_wcdma.alarm_type_id
     *
     * @return the value of unicom_alarm_wcdma.alarm_type_id
     *
     * @mbggenerated
     */
    public String getAlarmTypeId() {
        return alarmTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_alarm_wcdma.alarm_type_id
     *
     * @param alarmTypeId the value for unicom_alarm_wcdma.alarm_type_id
     *
     * @mbggenerated
     */
    public void setAlarmTypeId(String alarmTypeId) {
        this.alarmTypeId = alarmTypeId == null ? null : alarmTypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_alarm_wcdma.cell_name
     *
     * @return the value of unicom_alarm_wcdma.cell_name
     *
     * @mbggenerated
     */
    public String getCellName() {
        return cellName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_alarm_wcdma.cell_name
     *
     * @param cellName the value for unicom_alarm_wcdma.cell_name
     *
     * @mbggenerated
     */
    public void setCellName(String cellName) {
        this.cellName = cellName == null ? null : cellName.trim();
    }
}