package com.hongshen.sran_service.entity;

import java.io.Serializable;

public class UnicomRoomWcdma implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_room_wcdma.room
     *
     * @mbggenerated
     */
    private String room;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_room_wcdma.longitude
     *
     * @mbggenerated
     */
    private String longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_room_wcdma.latitude
     *
     * @mbggenerated
     */
    private String latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_room_wcdma.floors
     *
     * @mbggenerated
     */
    private String floors;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table unicom_room_wcdma
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_room_wcdma.room
     *
     * @return the value of unicom_room_wcdma.room
     *
     * @mbggenerated
     */
    public String getRoom() {
        return room;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_room_wcdma.room
     *
     * @param room the value for unicom_room_wcdma.room
     *
     * @mbggenerated
     */
    public void setRoom(String room) {
        this.room = room == null ? null : room.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_room_wcdma.longitude
     *
     * @return the value of unicom_room_wcdma.longitude
     *
     * @mbggenerated
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_room_wcdma.longitude
     *
     * @param longitude the value for unicom_room_wcdma.longitude
     *
     * @mbggenerated
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_room_wcdma.latitude
     *
     * @return the value of unicom_room_wcdma.latitude
     *
     * @mbggenerated
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_room_wcdma.latitude
     *
     * @param latitude the value for unicom_room_wcdma.latitude
     *
     * @mbggenerated
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_room_wcdma.floors
     *
     * @return the value of unicom_room_wcdma.floors
     *
     * @mbggenerated
     */
    public String getFloors() {
        return floors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_room_wcdma.floors
     *
     * @param floors the value for unicom_room_wcdma.floors
     *
     * @mbggenerated
     */
    public void setFloors(String floors) {
        this.floors = floors == null ? null : floors.trim();
    }
}