package com.hongshen.sran_service.entity;

import java.io.Serializable;

public class UnicomCellWcdma implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_cell_wcdma.cell_name
     *
     * @mbggenerated
     */
    private String cellName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_cell_wcdma.node_name
     *
     * @mbggenerated
     */
    private String nodeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_cell_wcdma.cell_id
     *
     * @mbggenerated
     */
    private byte[] cellId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table unicom_cell_wcdma
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_cell_wcdma.cell_name
     *
     * @return the value of unicom_cell_wcdma.cell_name
     *
     * @mbggenerated
     */
    public String getCellName() {
        return cellName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_cell_wcdma.cell_name
     *
     * @param cellName the value for unicom_cell_wcdma.cell_name
     *
     * @mbggenerated
     */
    public void setCellName(String cellName) {
        this.cellName = cellName == null ? null : cellName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_cell_wcdma.node_name
     *
     * @return the value of unicom_cell_wcdma.node_name
     *
     * @mbggenerated
     */
    public String getNodeName() {
        return nodeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_cell_wcdma.node_name
     *
     * @param nodeName the value for unicom_cell_wcdma.node_name
     *
     * @mbggenerated
     */
    public void setNodeName(String nodeName) {
        this.nodeName = nodeName == null ? null : nodeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_cell_wcdma.cell_id
     *
     * @return the value of unicom_cell_wcdma.cell_id
     *
     * @mbggenerated
     */
    public byte[] getCellId() {
        return cellId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_cell_wcdma.cell_id
     *
     * @param cellId the value for unicom_cell_wcdma.cell_id
     *
     * @mbggenerated
     */
    public void setCellId(byte[] cellId) {
        this.cellId = cellId;
    }
}