package com.hongshen.sran_service.entity;

import java.io.Serializable;

public class UnicomAlarmIndex implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_alarm_index.alarm_name_id
     *
     * @mbggenerated
     */
    private String alarmNameId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_alarm_index.alarm_name
     *
     * @mbggenerated
     */
    private String alarmName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table unicom_alarm_index
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_alarm_index.alarm_name_id
     *
     * @return the value of unicom_alarm_index.alarm_name_id
     *
     * @mbggenerated
     */
    public String getAlarmNameId() {
        return alarmNameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_alarm_index.alarm_name_id
     *
     * @param alarmNameId the value for unicom_alarm_index.alarm_name_id
     *
     * @mbggenerated
     */
    public void setAlarmNameId(String alarmNameId) {
        this.alarmNameId = alarmNameId == null ? null : alarmNameId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_alarm_index.alarm_name
     *
     * @return the value of unicom_alarm_index.alarm_name
     *
     * @mbggenerated
     */
    public String getAlarmName() {
        return alarmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_alarm_index.alarm_name
     *
     * @param alarmName the value for unicom_alarm_index.alarm_name
     *
     * @mbggenerated
     */
    public void setAlarmName(String alarmName) {
        this.alarmName = alarmName == null ? null : alarmName.trim();
    }
}