package com.hongshen.sran_service.entity;

import java.io.Serializable;

public class UnicomNodeLte implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_node_lte.node_name
     *
     * @mbggenerated
     */
    private String nodeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_node_lte.group_name
     *
     * @mbggenerated
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_node_lte.station_name
     *
     * @mbggenerated
     */
    private String stationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_node_lte.longitude
     *
     * @mbggenerated
     */
    private String longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_node_lte.latitude
     *
     * @mbggenerated
     */
    private String latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_node_lte.swversion
     *
     * @mbggenerated
     */
    private String swversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_node_lte.license_user
     *
     * @mbggenerated
     */
    private String licenseUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_node_lte.mme
     *
     * @mbggenerated
     */
    private String mme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_node_lte.ip
     *
     * @mbggenerated
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_node_lte.enb_id
     *
     * @mbggenerated
     */
    private String enbId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table unicom_node_lte
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_node_lte.node_name
     *
     * @return the value of unicom_node_lte.node_name
     *
     * @mbggenerated
     */
    public String getNodeName() {
        return nodeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_node_lte.node_name
     *
     * @param nodeName the value for unicom_node_lte.node_name
     *
     * @mbggenerated
     */
    public void setNodeName(String nodeName) {
        this.nodeName = nodeName == null ? null : nodeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_node_lte.group_name
     *
     * @return the value of unicom_node_lte.group_name
     *
     * @mbggenerated
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_node_lte.group_name
     *
     * @param groupName the value for unicom_node_lte.group_name
     *
     * @mbggenerated
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_node_lte.station_name
     *
     * @return the value of unicom_node_lte.station_name
     *
     * @mbggenerated
     */
    public String getStationName() {
        return stationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_node_lte.station_name
     *
     * @param stationName the value for unicom_node_lte.station_name
     *
     * @mbggenerated
     */
    public void setStationName(String stationName) {
        this.stationName = stationName == null ? null : stationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_node_lte.longitude
     *
     * @return the value of unicom_node_lte.longitude
     *
     * @mbggenerated
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_node_lte.longitude
     *
     * @param longitude the value for unicom_node_lte.longitude
     *
     * @mbggenerated
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_node_lte.latitude
     *
     * @return the value of unicom_node_lte.latitude
     *
     * @mbggenerated
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_node_lte.latitude
     *
     * @param latitude the value for unicom_node_lte.latitude
     *
     * @mbggenerated
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_node_lte.swversion
     *
     * @return the value of unicom_node_lte.swversion
     *
     * @mbggenerated
     */
    public String getSwversion() {
        return swversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_node_lte.swversion
     *
     * @param swversion the value for unicom_node_lte.swversion
     *
     * @mbggenerated
     */
    public void setSwversion(String swversion) {
        this.swversion = swversion == null ? null : swversion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_node_lte.license_user
     *
     * @return the value of unicom_node_lte.license_user
     *
     * @mbggenerated
     */
    public String getLicenseUser() {
        return licenseUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_node_lte.license_user
     *
     * @param licenseUser the value for unicom_node_lte.license_user
     *
     * @mbggenerated
     */
    public void setLicenseUser(String licenseUser) {
        this.licenseUser = licenseUser == null ? null : licenseUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_node_lte.mme
     *
     * @return the value of unicom_node_lte.mme
     *
     * @mbggenerated
     */
    public String getMme() {
        return mme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_node_lte.mme
     *
     * @param mme the value for unicom_node_lte.mme
     *
     * @mbggenerated
     */
    public void setMme(String mme) {
        this.mme = mme == null ? null : mme.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_node_lte.ip
     *
     * @return the value of unicom_node_lte.ip
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_node_lte.ip
     *
     * @param ip the value for unicom_node_lte.ip
     *
     * @mbggenerated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_node_lte.enb_id
     *
     * @return the value of unicom_node_lte.enb_id
     *
     * @mbggenerated
     */
    public String getEnbId() {
        return enbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_node_lte.enb_id
     *
     * @param enbId the value for unicom_node_lte.enb_id
     *
     * @mbggenerated
     */
    public void setEnbId(String enbId) {
        this.enbId = enbId == null ? null : enbId.trim();
    }
}