package com.hongshen.sran_service.entity;

import java.io.Serializable;

public class UnicomGroupTaskWcdma implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_group_task_wcdma.task_name
     *
     * @mbggenerated
     */
    private String taskName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_group_task_wcdma.net_list
     *
     * @mbggenerated
     */
    private String netList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_group_task_wcdma.command_list
     *
     * @mbggenerated
     */
    private String commandList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table unicom_group_task_wcdma
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_group_task_wcdma.task_name
     *
     * @return the value of unicom_group_task_wcdma.task_name
     *
     * @mbggenerated
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_group_task_wcdma.task_name
     *
     * @param taskName the value for unicom_group_task_wcdma.task_name
     *
     * @mbggenerated
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName == null ? null : taskName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_group_task_wcdma.net_list
     *
     * @return the value of unicom_group_task_wcdma.net_list
     *
     * @mbggenerated
     */
    public String getNetList() {
        return netList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_group_task_wcdma.net_list
     *
     * @param netList the value for unicom_group_task_wcdma.net_list
     *
     * @mbggenerated
     */
    public void setNetList(String netList) {
        this.netList = netList == null ? null : netList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_group_task_wcdma.command_list
     *
     * @return the value of unicom_group_task_wcdma.command_list
     *
     * @mbggenerated
     */
    public String getCommandList() {
        return commandList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_group_task_wcdma.command_list
     *
     * @param commandList the value for unicom_group_task_wcdma.command_list
     *
     * @mbggenerated
     */
    public void setCommandList(String commandList) {
        this.commandList = commandList == null ? null : commandList.trim();
    }
}