package com.hongshen.sran_service.entity;

import java.io.Serializable;

public class UnicomAuthorityLte implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_authority_lte.authority_name
     *
     * @mbggenerated
     */
    private String authorityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_authority_lte.list
     *
     * @mbggenerated
     */
    private String list;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table unicom_authority_lte
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_authority_lte.authority_name
     *
     * @return the value of unicom_authority_lte.authority_name
     *
     * @mbggenerated
     */
    public String getAuthorityName() {
        return authorityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_authority_lte.authority_name
     *
     * @param authorityName the value for unicom_authority_lte.authority_name
     *
     * @mbggenerated
     */
    public void setAuthorityName(String authorityName) {
        this.authorityName = authorityName == null ? null : authorityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_authority_lte.list
     *
     * @return the value of unicom_authority_lte.list
     *
     * @mbggenerated
     */
    public String getList() {
        return list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_authority_lte.list
     *
     * @param list the value for unicom_authority_lte.list
     *
     * @mbggenerated
     */
    public void setList(String list) {
        this.list = list == null ? null : list.trim();
    }
}