package com.hongshen.sran_service.entity;

import java.io.Serializable;
import java.util.Date;

public class UnicomCounterHistoryLte implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.time
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter1
     *
     * @mbggenerated
     */
    private String counter1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter2
     *
     * @mbggenerated
     */
    private String counter2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter3
     *
     * @mbggenerated
     */
    private String counter3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter4
     *
     * @mbggenerated
     */
    private String counter4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter5
     *
     * @mbggenerated
     */
    private String counter5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter6
     *
     * @mbggenerated
     */
    private String counter6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter7
     *
     * @mbggenerated
     */
    private String counter7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter8
     *
     * @mbggenerated
     */
    private String counter8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter9
     *
     * @mbggenerated
     */
    private String counter9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter10
     *
     * @mbggenerated
     */
    private String counter10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter11
     *
     * @mbggenerated
     */
    private String counter11;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter12
     *
     * @mbggenerated
     */
    private String counter12;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter13
     *
     * @mbggenerated
     */
    private String counter13;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter14
     *
     * @mbggenerated
     */
    private String counter14;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter15
     *
     * @mbggenerated
     */
    private String counter15;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter16
     *
     * @mbggenerated
     */
    private String counter16;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter17
     *
     * @mbggenerated
     */
    private String counter17;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter18
     *
     * @mbggenerated
     */
    private String counter18;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter19
     *
     * @mbggenerated
     */
    private String counter19;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter20
     *
     * @mbggenerated
     */
    private String counter20;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter21
     *
     * @mbggenerated
     */
    private String counter21;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter22
     *
     * @mbggenerated
     */
    private String counter22;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter23
     *
     * @mbggenerated
     */
    private String counter23;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter24
     *
     * @mbggenerated
     */
    private String counter24;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter25
     *
     * @mbggenerated
     */
    private String counter25;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter26
     *
     * @mbggenerated
     */
    private String counter26;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter27
     *
     * @mbggenerated
     */
    private String counter27;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter28
     *
     * @mbggenerated
     */
    private String counter28;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter29
     *
     * @mbggenerated
     */
    private String counter29;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter30
     *
     * @mbggenerated
     */
    private String counter30;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter31
     *
     * @mbggenerated
     */
    private String counter31;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter32
     *
     * @mbggenerated
     */
    private String counter32;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter33
     *
     * @mbggenerated
     */
    private String counter33;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter34
     *
     * @mbggenerated
     */
    private String counter34;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter35
     *
     * @mbggenerated
     */
    private String counter35;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter36
     *
     * @mbggenerated
     */
    private String counter36;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter37
     *
     * @mbggenerated
     */
    private String counter37;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter38
     *
     * @mbggenerated
     */
    private String counter38;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter39
     *
     * @mbggenerated
     */
    private String counter39;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter40
     *
     * @mbggenerated
     */
    private String counter40;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter41
     *
     * @mbggenerated
     */
    private String counter41;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter42
     *
     * @mbggenerated
     */
    private String counter42;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter43
     *
     * @mbggenerated
     */
    private String counter43;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter44
     *
     * @mbggenerated
     */
    private String counter44;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter45
     *
     * @mbggenerated
     */
    private String counter45;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter46
     *
     * @mbggenerated
     */
    private String counter46;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter47
     *
     * @mbggenerated
     */
    private String counter47;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter48
     *
     * @mbggenerated
     */
    private String counter48;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter49
     *
     * @mbggenerated
     */
    private String counter49;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter50
     *
     * @mbggenerated
     */
    private String counter50;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter51
     *
     * @mbggenerated
     */
    private String counter51;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter52
     *
     * @mbggenerated
     */
    private String counter52;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter53
     *
     * @mbggenerated
     */
    private String counter53;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter54
     *
     * @mbggenerated
     */
    private String counter54;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_counter_history_lte.counter55
     *
     * @mbggenerated
     */
    private String counter55;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table unicom_counter_history_lte
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.name
     *
     * @return the value of unicom_counter_history_lte.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.name
     *
     * @param name the value for unicom_counter_history_lte.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.time
     *
     * @return the value of unicom_counter_history_lte.time
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.time
     *
     * @param time the value for unicom_counter_history_lte.time
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter1
     *
     * @return the value of unicom_counter_history_lte.counter1
     *
     * @mbggenerated
     */
    public String getCounter1() {
        return counter1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter1
     *
     * @param counter1 the value for unicom_counter_history_lte.counter1
     *
     * @mbggenerated
     */
    public void setCounter1(String counter1) {
        this.counter1 = counter1 == null ? null : counter1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter2
     *
     * @return the value of unicom_counter_history_lte.counter2
     *
     * @mbggenerated
     */
    public String getCounter2() {
        return counter2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter2
     *
     * @param counter2 the value for unicom_counter_history_lte.counter2
     *
     * @mbggenerated
     */
    public void setCounter2(String counter2) {
        this.counter2 = counter2 == null ? null : counter2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter3
     *
     * @return the value of unicom_counter_history_lte.counter3
     *
     * @mbggenerated
     */
    public String getCounter3() {
        return counter3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter3
     *
     * @param counter3 the value for unicom_counter_history_lte.counter3
     *
     * @mbggenerated
     */
    public void setCounter3(String counter3) {
        this.counter3 = counter3 == null ? null : counter3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter4
     *
     * @return the value of unicom_counter_history_lte.counter4
     *
     * @mbggenerated
     */
    public String getCounter4() {
        return counter4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter4
     *
     * @param counter4 the value for unicom_counter_history_lte.counter4
     *
     * @mbggenerated
     */
    public void setCounter4(String counter4) {
        this.counter4 = counter4 == null ? null : counter4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter5
     *
     * @return the value of unicom_counter_history_lte.counter5
     *
     * @mbggenerated
     */
    public String getCounter5() {
        return counter5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter5
     *
     * @param counter5 the value for unicom_counter_history_lte.counter5
     *
     * @mbggenerated
     */
    public void setCounter5(String counter5) {
        this.counter5 = counter5 == null ? null : counter5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter6
     *
     * @return the value of unicom_counter_history_lte.counter6
     *
     * @mbggenerated
     */
    public String getCounter6() {
        return counter6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter6
     *
     * @param counter6 the value for unicom_counter_history_lte.counter6
     *
     * @mbggenerated
     */
    public void setCounter6(String counter6) {
        this.counter6 = counter6 == null ? null : counter6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter7
     *
     * @return the value of unicom_counter_history_lte.counter7
     *
     * @mbggenerated
     */
    public String getCounter7() {
        return counter7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter7
     *
     * @param counter7 the value for unicom_counter_history_lte.counter7
     *
     * @mbggenerated
     */
    public void setCounter7(String counter7) {
        this.counter7 = counter7 == null ? null : counter7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter8
     *
     * @return the value of unicom_counter_history_lte.counter8
     *
     * @mbggenerated
     */
    public String getCounter8() {
        return counter8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter8
     *
     * @param counter8 the value for unicom_counter_history_lte.counter8
     *
     * @mbggenerated
     */
    public void setCounter8(String counter8) {
        this.counter8 = counter8 == null ? null : counter8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter9
     *
     * @return the value of unicom_counter_history_lte.counter9
     *
     * @mbggenerated
     */
    public String getCounter9() {
        return counter9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter9
     *
     * @param counter9 the value for unicom_counter_history_lte.counter9
     *
     * @mbggenerated
     */
    public void setCounter9(String counter9) {
        this.counter9 = counter9 == null ? null : counter9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter10
     *
     * @return the value of unicom_counter_history_lte.counter10
     *
     * @mbggenerated
     */
    public String getCounter10() {
        return counter10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter10
     *
     * @param counter10 the value for unicom_counter_history_lte.counter10
     *
     * @mbggenerated
     */
    public void setCounter10(String counter10) {
        this.counter10 = counter10 == null ? null : counter10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter11
     *
     * @return the value of unicom_counter_history_lte.counter11
     *
     * @mbggenerated
     */
    public String getCounter11() {
        return counter11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter11
     *
     * @param counter11 the value for unicom_counter_history_lte.counter11
     *
     * @mbggenerated
     */
    public void setCounter11(String counter11) {
        this.counter11 = counter11 == null ? null : counter11.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter12
     *
     * @return the value of unicom_counter_history_lte.counter12
     *
     * @mbggenerated
     */
    public String getCounter12() {
        return counter12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter12
     *
     * @param counter12 the value for unicom_counter_history_lte.counter12
     *
     * @mbggenerated
     */
    public void setCounter12(String counter12) {
        this.counter12 = counter12 == null ? null : counter12.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter13
     *
     * @return the value of unicom_counter_history_lte.counter13
     *
     * @mbggenerated
     */
    public String getCounter13() {
        return counter13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter13
     *
     * @param counter13 the value for unicom_counter_history_lte.counter13
     *
     * @mbggenerated
     */
    public void setCounter13(String counter13) {
        this.counter13 = counter13 == null ? null : counter13.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter14
     *
     * @return the value of unicom_counter_history_lte.counter14
     *
     * @mbggenerated
     */
    public String getCounter14() {
        return counter14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter14
     *
     * @param counter14 the value for unicom_counter_history_lte.counter14
     *
     * @mbggenerated
     */
    public void setCounter14(String counter14) {
        this.counter14 = counter14 == null ? null : counter14.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter15
     *
     * @return the value of unicom_counter_history_lte.counter15
     *
     * @mbggenerated
     */
    public String getCounter15() {
        return counter15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter15
     *
     * @param counter15 the value for unicom_counter_history_lte.counter15
     *
     * @mbggenerated
     */
    public void setCounter15(String counter15) {
        this.counter15 = counter15 == null ? null : counter15.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter16
     *
     * @return the value of unicom_counter_history_lte.counter16
     *
     * @mbggenerated
     */
    public String getCounter16() {
        return counter16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter16
     *
     * @param counter16 the value for unicom_counter_history_lte.counter16
     *
     * @mbggenerated
     */
    public void setCounter16(String counter16) {
        this.counter16 = counter16 == null ? null : counter16.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter17
     *
     * @return the value of unicom_counter_history_lte.counter17
     *
     * @mbggenerated
     */
    public String getCounter17() {
        return counter17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter17
     *
     * @param counter17 the value for unicom_counter_history_lte.counter17
     *
     * @mbggenerated
     */
    public void setCounter17(String counter17) {
        this.counter17 = counter17 == null ? null : counter17.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter18
     *
     * @return the value of unicom_counter_history_lte.counter18
     *
     * @mbggenerated
     */
    public String getCounter18() {
        return counter18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter18
     *
     * @param counter18 the value for unicom_counter_history_lte.counter18
     *
     * @mbggenerated
     */
    public void setCounter18(String counter18) {
        this.counter18 = counter18 == null ? null : counter18.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter19
     *
     * @return the value of unicom_counter_history_lte.counter19
     *
     * @mbggenerated
     */
    public String getCounter19() {
        return counter19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter19
     *
     * @param counter19 the value for unicom_counter_history_lte.counter19
     *
     * @mbggenerated
     */
    public void setCounter19(String counter19) {
        this.counter19 = counter19 == null ? null : counter19.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter20
     *
     * @return the value of unicom_counter_history_lte.counter20
     *
     * @mbggenerated
     */
    public String getCounter20() {
        return counter20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter20
     *
     * @param counter20 the value for unicom_counter_history_lte.counter20
     *
     * @mbggenerated
     */
    public void setCounter20(String counter20) {
        this.counter20 = counter20 == null ? null : counter20.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter21
     *
     * @return the value of unicom_counter_history_lte.counter21
     *
     * @mbggenerated
     */
    public String getCounter21() {
        return counter21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter21
     *
     * @param counter21 the value for unicom_counter_history_lte.counter21
     *
     * @mbggenerated
     */
    public void setCounter21(String counter21) {
        this.counter21 = counter21 == null ? null : counter21.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter22
     *
     * @return the value of unicom_counter_history_lte.counter22
     *
     * @mbggenerated
     */
    public String getCounter22() {
        return counter22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter22
     *
     * @param counter22 the value for unicom_counter_history_lte.counter22
     *
     * @mbggenerated
     */
    public void setCounter22(String counter22) {
        this.counter22 = counter22 == null ? null : counter22.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter23
     *
     * @return the value of unicom_counter_history_lte.counter23
     *
     * @mbggenerated
     */
    public String getCounter23() {
        return counter23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter23
     *
     * @param counter23 the value for unicom_counter_history_lte.counter23
     *
     * @mbggenerated
     */
    public void setCounter23(String counter23) {
        this.counter23 = counter23 == null ? null : counter23.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter24
     *
     * @return the value of unicom_counter_history_lte.counter24
     *
     * @mbggenerated
     */
    public String getCounter24() {
        return counter24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter24
     *
     * @param counter24 the value for unicom_counter_history_lte.counter24
     *
     * @mbggenerated
     */
    public void setCounter24(String counter24) {
        this.counter24 = counter24 == null ? null : counter24.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter25
     *
     * @return the value of unicom_counter_history_lte.counter25
     *
     * @mbggenerated
     */
    public String getCounter25() {
        return counter25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter25
     *
     * @param counter25 the value for unicom_counter_history_lte.counter25
     *
     * @mbggenerated
     */
    public void setCounter25(String counter25) {
        this.counter25 = counter25 == null ? null : counter25.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter26
     *
     * @return the value of unicom_counter_history_lte.counter26
     *
     * @mbggenerated
     */
    public String getCounter26() {
        return counter26;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter26
     *
     * @param counter26 the value for unicom_counter_history_lte.counter26
     *
     * @mbggenerated
     */
    public void setCounter26(String counter26) {
        this.counter26 = counter26 == null ? null : counter26.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter27
     *
     * @return the value of unicom_counter_history_lte.counter27
     *
     * @mbggenerated
     */
    public String getCounter27() {
        return counter27;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter27
     *
     * @param counter27 the value for unicom_counter_history_lte.counter27
     *
     * @mbggenerated
     */
    public void setCounter27(String counter27) {
        this.counter27 = counter27 == null ? null : counter27.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter28
     *
     * @return the value of unicom_counter_history_lte.counter28
     *
     * @mbggenerated
     */
    public String getCounter28() {
        return counter28;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter28
     *
     * @param counter28 the value for unicom_counter_history_lte.counter28
     *
     * @mbggenerated
     */
    public void setCounter28(String counter28) {
        this.counter28 = counter28 == null ? null : counter28.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter29
     *
     * @return the value of unicom_counter_history_lte.counter29
     *
     * @mbggenerated
     */
    public String getCounter29() {
        return counter29;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter29
     *
     * @param counter29 the value for unicom_counter_history_lte.counter29
     *
     * @mbggenerated
     */
    public void setCounter29(String counter29) {
        this.counter29 = counter29 == null ? null : counter29.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter30
     *
     * @return the value of unicom_counter_history_lte.counter30
     *
     * @mbggenerated
     */
    public String getCounter30() {
        return counter30;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter30
     *
     * @param counter30 the value for unicom_counter_history_lte.counter30
     *
     * @mbggenerated
     */
    public void setCounter30(String counter30) {
        this.counter30 = counter30 == null ? null : counter30.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter31
     *
     * @return the value of unicom_counter_history_lte.counter31
     *
     * @mbggenerated
     */
    public String getCounter31() {
        return counter31;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter31
     *
     * @param counter31 the value for unicom_counter_history_lte.counter31
     *
     * @mbggenerated
     */
    public void setCounter31(String counter31) {
        this.counter31 = counter31 == null ? null : counter31.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter32
     *
     * @return the value of unicom_counter_history_lte.counter32
     *
     * @mbggenerated
     */
    public String getCounter32() {
        return counter32;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter32
     *
     * @param counter32 the value for unicom_counter_history_lte.counter32
     *
     * @mbggenerated
     */
    public void setCounter32(String counter32) {
        this.counter32 = counter32 == null ? null : counter32.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter33
     *
     * @return the value of unicom_counter_history_lte.counter33
     *
     * @mbggenerated
     */
    public String getCounter33() {
        return counter33;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter33
     *
     * @param counter33 the value for unicom_counter_history_lte.counter33
     *
     * @mbggenerated
     */
    public void setCounter33(String counter33) {
        this.counter33 = counter33 == null ? null : counter33.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter34
     *
     * @return the value of unicom_counter_history_lte.counter34
     *
     * @mbggenerated
     */
    public String getCounter34() {
        return counter34;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter34
     *
     * @param counter34 the value for unicom_counter_history_lte.counter34
     *
     * @mbggenerated
     */
    public void setCounter34(String counter34) {
        this.counter34 = counter34 == null ? null : counter34.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter35
     *
     * @return the value of unicom_counter_history_lte.counter35
     *
     * @mbggenerated
     */
    public String getCounter35() {
        return counter35;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter35
     *
     * @param counter35 the value for unicom_counter_history_lte.counter35
     *
     * @mbggenerated
     */
    public void setCounter35(String counter35) {
        this.counter35 = counter35 == null ? null : counter35.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter36
     *
     * @return the value of unicom_counter_history_lte.counter36
     *
     * @mbggenerated
     */
    public String getCounter36() {
        return counter36;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter36
     *
     * @param counter36 the value for unicom_counter_history_lte.counter36
     *
     * @mbggenerated
     */
    public void setCounter36(String counter36) {
        this.counter36 = counter36 == null ? null : counter36.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter37
     *
     * @return the value of unicom_counter_history_lte.counter37
     *
     * @mbggenerated
     */
    public String getCounter37() {
        return counter37;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter37
     *
     * @param counter37 the value for unicom_counter_history_lte.counter37
     *
     * @mbggenerated
     */
    public void setCounter37(String counter37) {
        this.counter37 = counter37 == null ? null : counter37.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter38
     *
     * @return the value of unicom_counter_history_lte.counter38
     *
     * @mbggenerated
     */
    public String getCounter38() {
        return counter38;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter38
     *
     * @param counter38 the value for unicom_counter_history_lte.counter38
     *
     * @mbggenerated
     */
    public void setCounter38(String counter38) {
        this.counter38 = counter38 == null ? null : counter38.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter39
     *
     * @return the value of unicom_counter_history_lte.counter39
     *
     * @mbggenerated
     */
    public String getCounter39() {
        return counter39;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter39
     *
     * @param counter39 the value for unicom_counter_history_lte.counter39
     *
     * @mbggenerated
     */
    public void setCounter39(String counter39) {
        this.counter39 = counter39 == null ? null : counter39.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter40
     *
     * @return the value of unicom_counter_history_lte.counter40
     *
     * @mbggenerated
     */
    public String getCounter40() {
        return counter40;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter40
     *
     * @param counter40 the value for unicom_counter_history_lte.counter40
     *
     * @mbggenerated
     */
    public void setCounter40(String counter40) {
        this.counter40 = counter40 == null ? null : counter40.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter41
     *
     * @return the value of unicom_counter_history_lte.counter41
     *
     * @mbggenerated
     */
    public String getCounter41() {
        return counter41;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter41
     *
     * @param counter41 the value for unicom_counter_history_lte.counter41
     *
     * @mbggenerated
     */
    public void setCounter41(String counter41) {
        this.counter41 = counter41 == null ? null : counter41.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter42
     *
     * @return the value of unicom_counter_history_lte.counter42
     *
     * @mbggenerated
     */
    public String getCounter42() {
        return counter42;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter42
     *
     * @param counter42 the value for unicom_counter_history_lte.counter42
     *
     * @mbggenerated
     */
    public void setCounter42(String counter42) {
        this.counter42 = counter42 == null ? null : counter42.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter43
     *
     * @return the value of unicom_counter_history_lte.counter43
     *
     * @mbggenerated
     */
    public String getCounter43() {
        return counter43;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter43
     *
     * @param counter43 the value for unicom_counter_history_lte.counter43
     *
     * @mbggenerated
     */
    public void setCounter43(String counter43) {
        this.counter43 = counter43 == null ? null : counter43.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter44
     *
     * @return the value of unicom_counter_history_lte.counter44
     *
     * @mbggenerated
     */
    public String getCounter44() {
        return counter44;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter44
     *
     * @param counter44 the value for unicom_counter_history_lte.counter44
     *
     * @mbggenerated
     */
    public void setCounter44(String counter44) {
        this.counter44 = counter44 == null ? null : counter44.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter45
     *
     * @return the value of unicom_counter_history_lte.counter45
     *
     * @mbggenerated
     */
    public String getCounter45() {
        return counter45;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter45
     *
     * @param counter45 the value for unicom_counter_history_lte.counter45
     *
     * @mbggenerated
     */
    public void setCounter45(String counter45) {
        this.counter45 = counter45 == null ? null : counter45.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter46
     *
     * @return the value of unicom_counter_history_lte.counter46
     *
     * @mbggenerated
     */
    public String getCounter46() {
        return counter46;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter46
     *
     * @param counter46 the value for unicom_counter_history_lte.counter46
     *
     * @mbggenerated
     */
    public void setCounter46(String counter46) {
        this.counter46 = counter46 == null ? null : counter46.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter47
     *
     * @return the value of unicom_counter_history_lte.counter47
     *
     * @mbggenerated
     */
    public String getCounter47() {
        return counter47;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter47
     *
     * @param counter47 the value for unicom_counter_history_lte.counter47
     *
     * @mbggenerated
     */
    public void setCounter47(String counter47) {
        this.counter47 = counter47 == null ? null : counter47.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter48
     *
     * @return the value of unicom_counter_history_lte.counter48
     *
     * @mbggenerated
     */
    public String getCounter48() {
        return counter48;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter48
     *
     * @param counter48 the value for unicom_counter_history_lte.counter48
     *
     * @mbggenerated
     */
    public void setCounter48(String counter48) {
        this.counter48 = counter48 == null ? null : counter48.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter49
     *
     * @return the value of unicom_counter_history_lte.counter49
     *
     * @mbggenerated
     */
    public String getCounter49() {
        return counter49;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter49
     *
     * @param counter49 the value for unicom_counter_history_lte.counter49
     *
     * @mbggenerated
     */
    public void setCounter49(String counter49) {
        this.counter49 = counter49 == null ? null : counter49.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter50
     *
     * @return the value of unicom_counter_history_lte.counter50
     *
     * @mbggenerated
     */
    public String getCounter50() {
        return counter50;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter50
     *
     * @param counter50 the value for unicom_counter_history_lte.counter50
     *
     * @mbggenerated
     */
    public void setCounter50(String counter50) {
        this.counter50 = counter50 == null ? null : counter50.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter51
     *
     * @return the value of unicom_counter_history_lte.counter51
     *
     * @mbggenerated
     */
    public String getCounter51() {
        return counter51;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter51
     *
     * @param counter51 the value for unicom_counter_history_lte.counter51
     *
     * @mbggenerated
     */
    public void setCounter51(String counter51) {
        this.counter51 = counter51 == null ? null : counter51.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter52
     *
     * @return the value of unicom_counter_history_lte.counter52
     *
     * @mbggenerated
     */
    public String getCounter52() {
        return counter52;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter52
     *
     * @param counter52 the value for unicom_counter_history_lte.counter52
     *
     * @mbggenerated
     */
    public void setCounter52(String counter52) {
        this.counter52 = counter52 == null ? null : counter52.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter53
     *
     * @return the value of unicom_counter_history_lte.counter53
     *
     * @mbggenerated
     */
    public String getCounter53() {
        return counter53;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter53
     *
     * @param counter53 the value for unicom_counter_history_lte.counter53
     *
     * @mbggenerated
     */
    public void setCounter53(String counter53) {
        this.counter53 = counter53 == null ? null : counter53.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter54
     *
     * @return the value of unicom_counter_history_lte.counter54
     *
     * @mbggenerated
     */
    public String getCounter54() {
        return counter54;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter54
     *
     * @param counter54 the value for unicom_counter_history_lte.counter54
     *
     * @mbggenerated
     */
    public void setCounter54(String counter54) {
        this.counter54 = counter54 == null ? null : counter54.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_counter_history_lte.counter55
     *
     * @return the value of unicom_counter_history_lte.counter55
     *
     * @mbggenerated
     */
    public String getCounter55() {
        return counter55;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_counter_history_lte.counter55
     *
     * @param counter55 the value for unicom_counter_history_lte.counter55
     *
     * @mbggenerated
     */
    public void setCounter55(String counter55) {
        this.counter55 = counter55 == null ? null : counter55.trim();
    }
}