package com.hongshen.sran_service.entity;

import java.io.Serializable;

public class UnicomUserAuhorityLte implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_user_auhority_lte.login_name
     *
     * @mbggenerated
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_user_auhority_lte.authority_name
     *
     * @mbggenerated
     */
    private String authorityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table unicom_user_auhority_lte
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_user_auhority_lte.login_name
     *
     * @return the value of unicom_user_auhority_lte.login_name
     *
     * @mbggenerated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_user_auhority_lte.login_name
     *
     * @param loginName the value for unicom_user_auhority_lte.login_name
     *
     * @mbggenerated
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_user_auhority_lte.authority_name
     *
     * @return the value of unicom_user_auhority_lte.authority_name
     *
     * @mbggenerated
     */
    public String getAuthorityName() {
        return authorityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_user_auhority_lte.authority_name
     *
     * @param authorityName the value for unicom_user_auhority_lte.authority_name
     *
     * @mbggenerated
     */
    public void setAuthorityName(String authorityName) {
        this.authorityName = authorityName == null ? null : authorityName.trim();
    }
}