package com.hongshen.sran_service.entity;

import java.io.Serializable;

public class UnicomTaskWcdmaWithBLOBs extends UnicomTaskWcdma implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_task_wcdma.command
     *
     * @mbggenerated
     */
    private String command;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_task_wcdma.script
     *
     * @mbggenerated
     */
    private String script;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table unicom_task_wcdma
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_task_wcdma.command
     *
     * @return the value of unicom_task_wcdma.command
     *
     * @mbggenerated
     */
    public String getCommand() {
        return command;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_task_wcdma.command
     *
     * @param command the value for unicom_task_wcdma.command
     *
     * @mbggenerated
     */
    public void setCommand(String command) {
        this.command = command == null ? null : command.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_task_wcdma.script
     *
     * @return the value of unicom_task_wcdma.script
     *
     * @mbggenerated
     */
    public String getScript() {
        return script;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_task_wcdma.script
     *
     * @param script the value for unicom_task_wcdma.script
     *
     * @mbggenerated
     */
    public void setScript(String script) {
        this.script = script == null ? null : script.trim();
    }
}