package com.hongshen.sran_service.entity;

import java.io.Serializable;

public class UnicomUserTaskWcdmaKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_user_task_wcdma.login_name
     *
     * @mbggenerated
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_user_task_wcdma.taskId
     *
     * @mbggenerated
     */
    private Integer taskid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table unicom_user_task_wcdma
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_user_task_wcdma.login_name
     *
     * @return the value of unicom_user_task_wcdma.login_name
     *
     * @mbggenerated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_user_task_wcdma.login_name
     *
     * @param loginName the value for unicom_user_task_wcdma.login_name
     *
     * @mbggenerated
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_user_task_wcdma.taskId
     *
     * @return the value of unicom_user_task_wcdma.taskId
     *
     * @mbggenerated
     */
    public Integer getTaskid() {
        return taskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_user_task_wcdma.taskId
     *
     * @param taskid the value for unicom_user_task_wcdma.taskId
     *
     * @mbggenerated
     */
    public void setTaskid(Integer taskid) {
        this.taskid = taskid;
    }
}