package com.hongshen.sran_service.entity;

import java.io.Serializable;
import java.util.Date;

public class UnicomQuotaHistoryNodeWcdma implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_quota_history_node_wcdma.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_quota_history_node_wcdma.time
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_quota_history_node_wcdma.level
     *
     * @mbggenerated
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_quota_history_node_wcdma.CS_Iu_Sig_Suc
     *
     * @mbggenerated
     */
    private String csIuSigSuc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_quota_history_node_wcdma.PS_Iu_Sig_Suc
     *
     * @mbggenerated
     */
    private String psIuSigSuc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_quota_history_node_wcdma.Rrc_Suc
     *
     * @mbggenerated
     */
    private String rrcSuc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_quota_history_node_wcdma.PS_Rrc_Suc_Rate
     *
     * @mbggenerated
     */
    private String psRrcSucRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_quota_history_node_wcdma.Spch_Rrc_Suc_Rate
     *
     * @mbggenerated
     */
    private String spchRrcSucRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_quota_history_node_wcdma.Spch_Rab_Suc
     *
     * @mbggenerated
     */
    private String spchRabSuc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_quota_history_node_wcdma.PS_Rab_Succ
     *
     * @mbggenerated
     */
    private String psRabSucc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_quota_history_node_wcdma.SHO_Success
     *
     * @mbggenerated
     */
    private String shoSuccess;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_quota_history_node_wcdma.Spch_Drop
     *
     * @mbggenerated
     */
    private String spchDrop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_quota_history_node_wcdma.PS_Drop
     *
     * @mbggenerated
     */
    private String psDrop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table unicom_quota_history_node_wcdma
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_quota_history_node_wcdma.name
     *
     * @return the value of unicom_quota_history_node_wcdma.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_quota_history_node_wcdma.name
     *
     * @param name the value for unicom_quota_history_node_wcdma.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_quota_history_node_wcdma.time
     *
     * @return the value of unicom_quota_history_node_wcdma.time
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_quota_history_node_wcdma.time
     *
     * @param time the value for unicom_quota_history_node_wcdma.time
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_quota_history_node_wcdma.level
     *
     * @return the value of unicom_quota_history_node_wcdma.level
     *
     * @mbggenerated
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_quota_history_node_wcdma.level
     *
     * @param level the value for unicom_quota_history_node_wcdma.level
     *
     * @mbggenerated
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_quota_history_node_wcdma.CS_Iu_Sig_Suc
     *
     * @return the value of unicom_quota_history_node_wcdma.CS_Iu_Sig_Suc
     *
     * @mbggenerated
     */
    public String getCsIuSigSuc() {
        return csIuSigSuc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_quota_history_node_wcdma.CS_Iu_Sig_Suc
     *
     * @param csIuSigSuc the value for unicom_quota_history_node_wcdma.CS_Iu_Sig_Suc
     *
     * @mbggenerated
     */
    public void setCsIuSigSuc(String csIuSigSuc) {
        this.csIuSigSuc = csIuSigSuc == null ? null : csIuSigSuc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_quota_history_node_wcdma.PS_Iu_Sig_Suc
     *
     * @return the value of unicom_quota_history_node_wcdma.PS_Iu_Sig_Suc
     *
     * @mbggenerated
     */
    public String getPsIuSigSuc() {
        return psIuSigSuc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_quota_history_node_wcdma.PS_Iu_Sig_Suc
     *
     * @param psIuSigSuc the value for unicom_quota_history_node_wcdma.PS_Iu_Sig_Suc
     *
     * @mbggenerated
     */
    public void setPsIuSigSuc(String psIuSigSuc) {
        this.psIuSigSuc = psIuSigSuc == null ? null : psIuSigSuc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_quota_history_node_wcdma.Rrc_Suc
     *
     * @return the value of unicom_quota_history_node_wcdma.Rrc_Suc
     *
     * @mbggenerated
     */
    public String getRrcSuc() {
        return rrcSuc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_quota_history_node_wcdma.Rrc_Suc
     *
     * @param rrcSuc the value for unicom_quota_history_node_wcdma.Rrc_Suc
     *
     * @mbggenerated
     */
    public void setRrcSuc(String rrcSuc) {
        this.rrcSuc = rrcSuc == null ? null : rrcSuc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_quota_history_node_wcdma.PS_Rrc_Suc_Rate
     *
     * @return the value of unicom_quota_history_node_wcdma.PS_Rrc_Suc_Rate
     *
     * @mbggenerated
     */
    public String getPsRrcSucRate() {
        return psRrcSucRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_quota_history_node_wcdma.PS_Rrc_Suc_Rate
     *
     * @param psRrcSucRate the value for unicom_quota_history_node_wcdma.PS_Rrc_Suc_Rate
     *
     * @mbggenerated
     */
    public void setPsRrcSucRate(String psRrcSucRate) {
        this.psRrcSucRate = psRrcSucRate == null ? null : psRrcSucRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_quota_history_node_wcdma.Spch_Rrc_Suc_Rate
     *
     * @return the value of unicom_quota_history_node_wcdma.Spch_Rrc_Suc_Rate
     *
     * @mbggenerated
     */
    public String getSpchRrcSucRate() {
        return spchRrcSucRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_quota_history_node_wcdma.Spch_Rrc_Suc_Rate
     *
     * @param spchRrcSucRate the value for unicom_quota_history_node_wcdma.Spch_Rrc_Suc_Rate
     *
     * @mbggenerated
     */
    public void setSpchRrcSucRate(String spchRrcSucRate) {
        this.spchRrcSucRate = spchRrcSucRate == null ? null : spchRrcSucRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_quota_history_node_wcdma.Spch_Rab_Suc
     *
     * @return the value of unicom_quota_history_node_wcdma.Spch_Rab_Suc
     *
     * @mbggenerated
     */
    public String getSpchRabSuc() {
        return spchRabSuc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_quota_history_node_wcdma.Spch_Rab_Suc
     *
     * @param spchRabSuc the value for unicom_quota_history_node_wcdma.Spch_Rab_Suc
     *
     * @mbggenerated
     */
    public void setSpchRabSuc(String spchRabSuc) {
        this.spchRabSuc = spchRabSuc == null ? null : spchRabSuc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_quota_history_node_wcdma.PS_Rab_Succ
     *
     * @return the value of unicom_quota_history_node_wcdma.PS_Rab_Succ
     *
     * @mbggenerated
     */
    public String getPsRabSucc() {
        return psRabSucc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_quota_history_node_wcdma.PS_Rab_Succ
     *
     * @param psRabSucc the value for unicom_quota_history_node_wcdma.PS_Rab_Succ
     *
     * @mbggenerated
     */
    public void setPsRabSucc(String psRabSucc) {
        this.psRabSucc = psRabSucc == null ? null : psRabSucc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_quota_history_node_wcdma.SHO_Success
     *
     * @return the value of unicom_quota_history_node_wcdma.SHO_Success
     *
     * @mbggenerated
     */
    public String getShoSuccess() {
        return shoSuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_quota_history_node_wcdma.SHO_Success
     *
     * @param shoSuccess the value for unicom_quota_history_node_wcdma.SHO_Success
     *
     * @mbggenerated
     */
    public void setShoSuccess(String shoSuccess) {
        this.shoSuccess = shoSuccess == null ? null : shoSuccess.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_quota_history_node_wcdma.Spch_Drop
     *
     * @return the value of unicom_quota_history_node_wcdma.Spch_Drop
     *
     * @mbggenerated
     */
    public String getSpchDrop() {
        return spchDrop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_quota_history_node_wcdma.Spch_Drop
     *
     * @param spchDrop the value for unicom_quota_history_node_wcdma.Spch_Drop
     *
     * @mbggenerated
     */
    public void setSpchDrop(String spchDrop) {
        this.spchDrop = spchDrop == null ? null : spchDrop.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_quota_history_node_wcdma.PS_Drop
     *
     * @return the value of unicom_quota_history_node_wcdma.PS_Drop
     *
     * @mbggenerated
     */
    public String getPsDrop() {
        return psDrop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_quota_history_node_wcdma.PS_Drop
     *
     * @param psDrop the value for unicom_quota_history_node_wcdma.PS_Drop
     *
     * @mbggenerated
     */
    public void setPsDrop(String psDrop) {
        this.psDrop = psDrop == null ? null : psDrop.trim();
    }
}