package com.hongshen.sran_service.entity;

import java.io.Serializable;

public class UnicomNodeWcdma implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_node_wcdma.node_name
     *
     * @mbggenerated
     */
    private String nodeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_node_wcdma.group_name
     *
     * @mbggenerated
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_node_wcdma.station_name
     *
     * @mbggenerated
     */
    private String stationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_node_wcdma.rbsid
     *
     * @mbggenerated
     */
    private String rbsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_node_wcdma.ip
     *
     * @mbggenerated
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_node_wcdma.lac
     *
     * @mbggenerated
     */
    private String lac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_node_wcdma.latitude
     *
     * @mbggenerated
     */
    private String latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_node_wcdma.longitude
     *
     * @mbggenerated
     */
    private String longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_node_wcdma.swversion
     *
     * @mbggenerated
     */
    private String swversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_node_wcdma.isVip
     *
     * @mbggenerated
     */
    private Boolean isvip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table unicom_node_wcdma
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_node_wcdma.node_name
     *
     * @return the value of unicom_node_wcdma.node_name
     *
     * @mbggenerated
     */
    public String getNodeName() {
        return nodeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_node_wcdma.node_name
     *
     * @param nodeName the value for unicom_node_wcdma.node_name
     *
     * @mbggenerated
     */
    public void setNodeName(String nodeName) {
        this.nodeName = nodeName == null ? null : nodeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_node_wcdma.group_name
     *
     * @return the value of unicom_node_wcdma.group_name
     *
     * @mbggenerated
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_node_wcdma.group_name
     *
     * @param groupName the value for unicom_node_wcdma.group_name
     *
     * @mbggenerated
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_node_wcdma.station_name
     *
     * @return the value of unicom_node_wcdma.station_name
     *
     * @mbggenerated
     */
    public String getStationName() {
        return stationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_node_wcdma.station_name
     *
     * @param stationName the value for unicom_node_wcdma.station_name
     *
     * @mbggenerated
     */
    public void setStationName(String stationName) {
        this.stationName = stationName == null ? null : stationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_node_wcdma.rbsid
     *
     * @return the value of unicom_node_wcdma.rbsid
     *
     * @mbggenerated
     */
    public String getRbsid() {
        return rbsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_node_wcdma.rbsid
     *
     * @param rbsid the value for unicom_node_wcdma.rbsid
     *
     * @mbggenerated
     */
    public void setRbsid(String rbsid) {
        this.rbsid = rbsid == null ? null : rbsid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_node_wcdma.ip
     *
     * @return the value of unicom_node_wcdma.ip
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_node_wcdma.ip
     *
     * @param ip the value for unicom_node_wcdma.ip
     *
     * @mbggenerated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_node_wcdma.lac
     *
     * @return the value of unicom_node_wcdma.lac
     *
     * @mbggenerated
     */
    public String getLac() {
        return lac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_node_wcdma.lac
     *
     * @param lac the value for unicom_node_wcdma.lac
     *
     * @mbggenerated
     */
    public void setLac(String lac) {
        this.lac = lac == null ? null : lac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_node_wcdma.latitude
     *
     * @return the value of unicom_node_wcdma.latitude
     *
     * @mbggenerated
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_node_wcdma.latitude
     *
     * @param latitude the value for unicom_node_wcdma.latitude
     *
     * @mbggenerated
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_node_wcdma.longitude
     *
     * @return the value of unicom_node_wcdma.longitude
     *
     * @mbggenerated
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_node_wcdma.longitude
     *
     * @param longitude the value for unicom_node_wcdma.longitude
     *
     * @mbggenerated
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_node_wcdma.swversion
     *
     * @return the value of unicom_node_wcdma.swversion
     *
     * @mbggenerated
     */
    public String getSwversion() {
        return swversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_node_wcdma.swversion
     *
     * @param swversion the value for unicom_node_wcdma.swversion
     *
     * @mbggenerated
     */
    public void setSwversion(String swversion) {
        this.swversion = swversion == null ? null : swversion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_node_wcdma.isVip
     *
     * @return the value of unicom_node_wcdma.isVip
     *
     * @mbggenerated
     */
    public Boolean getIsvip() {
        return isvip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_node_wcdma.isVip
     *
     * @param isvip the value for unicom_node_wcdma.isVip
     *
     * @mbggenerated
     */
    public void setIsvip(Boolean isvip) {
        this.isvip = isvip;
    }
}