package com.hongshen.sran_service.entity;

import org.springframework.stereotype.Repository;

import java.io.Serializable;

@Repository
public class UnicomFormulaWcdma implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_formula_wcdma.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_formula_wcdma.quota_name
     *
     * @mbggenerated
     */
    private String quotaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_formula_wcdma.expression
     *
     * @mbggenerated
     */
    private String expression;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_formula_wcdma.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_formula_wcdma.status
     *
     * @mbggenerated
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_formula_wcdma.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table unicom_formula_wcdma
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_formula_wcdma.id
     *
     * @return the value of unicom_formula_wcdma.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_formula_wcdma.id
     *
     * @param id the value for unicom_formula_wcdma.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_formula_wcdma.quota_name
     *
     * @return the value of unicom_formula_wcdma.quota_name
     *
     * @mbggenerated
     */
    public String getQuotaName() {
        return quotaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_formula_wcdma.quota_name
     *
     * @param quotaName the value for unicom_formula_wcdma.quota_name
     *
     * @mbggenerated
     */
    public void setQuotaName(String quotaName) {
        this.quotaName = quotaName == null ? null : quotaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_formula_wcdma.expression
     *
     * @return the value of unicom_formula_wcdma.expression
     *
     * @mbggenerated
     */
    public String getExpression() {
        return expression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_formula_wcdma.expression
     *
     * @param expression the value for unicom_formula_wcdma.expression
     *
     * @mbggenerated
     */
    public void setExpression(String expression) {
        this.expression = expression == null ? null : expression.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_formula_wcdma.remark
     *
     * @return the value of unicom_formula_wcdma.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_formula_wcdma.remark
     *
     * @param remark the value for unicom_formula_wcdma.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_formula_wcdma.status
     *
     * @return the value of unicom_formula_wcdma.status
     *
     * @mbggenerated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_formula_wcdma.status
     *
     * @param status the value for unicom_formula_wcdma.status
     *
     * @mbggenerated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_formula_wcdma.type
     *
     * @return the value of unicom_formula_wcdma.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_formula_wcdma.type
     *
     * @param type the value for unicom_formula_wcdma.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}