package com.hongshen.sran_service.entity;

import java.io.Serializable;

public class UnicomFavoriteLte implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_favorite_lte.login_name
     *
     * @mbggenerated
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unicom_favorite_lte.list
     *
     * @mbggenerated
     */
    private String list;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table unicom_favorite_lte
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_favorite_lte.login_name
     *
     * @return the value of unicom_favorite_lte.login_name
     *
     * @mbggenerated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_favorite_lte.login_name
     *
     * @param loginName the value for unicom_favorite_lte.login_name
     *
     * @mbggenerated
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unicom_favorite_lte.list
     *
     * @return the value of unicom_favorite_lte.list
     *
     * @mbggenerated
     */
    public String getList() {
        return list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unicom_favorite_lte.list
     *
     * @param list the value for unicom_favorite_lte.list
     *
     * @mbggenerated
     */
    public void setList(String list) {
        this.list = list == null ? null : list.trim();
    }
}